### ISSUE TITLE
Modify website background color and text color.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#10]
provide soon.

**Comment by xiquinho** [comment]
when it would be soon?

**Comment by bo-io-gov-mo** [comment]
when you finalize and check in, we check out to adjust it. same as search layout adjust. I think it only  relate to css style.

**Comment by xiquinho** [comment]
where are you going to adjust it?

**Comment by bo-io-gov-mo** [comment]
At least home page and menu items and its link pages. May be relate to all website pages or only main css files. If we use TFS control version, you will know what was changed.

**Comment by xiquinho** [comment]
You need to tell me which pages exactly I need to checkout otherwise we could be modifying the same page at the same time. And before make any change is better tell me first what you want to change and how are you going to change it, at least the first times for I give advice where exactly you should make the changes.

**Comment by bo-io-gov-mo** [comment]
I will gather the information first.

**Comment by bo-io-gov-mo** [comment]
pls adjust following css:
[http://betan/cn/search/?o=0&tab=&s=0&q=macau](http://betan/cn/search/?o=0&tab=&s=0&q=macau
)
![image](https://cloud.githubusercontent.com/assets/19220046/18422586/a6e5d572-78cf-11e6-8249-727928042f59.png)

1.	Delete space char: 找到~~x~~15216~~x~~項結果 - 瀏覽:~~x~~1~~x~~/~~x~~609
2.	Change bo link text color: #888
3.	more blank line space: 23px
4.	Padding top: 7px ; padding-bottom:7px
5.	Add class: input-sm ; label text smaller: 1em;
6.	Fix search bar not align with button. Pls reference: http://192.168.3.63/cn/search

**Comment by xiquinho** [comment]
At http://192.168.3.63/cn/search  you replaced the dropdown select with a button, these are not the same things. To achieve this I will need to re-create:

a) a new button with dropdown functionalities
OR
b) a new dropdown with a button appearance.

None of these options are an easy task, and if possible it would take a lot of time, I don’t know how much, I already waste almost one day with this and not finish.

So, are you sure you want to replace the dropdown with a button?

**Comment by bo-io-gov-mo** [comment]
noted, keep existing select button is ok.

**Comment by xiquinho** [comment]
great, if it is OK, pl close.
