### ISSUE TITLE
remove some right side advertisement banner.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#11]
provide soon.

**Comment by bo-io-gov-mo** [comment]
Please keep these item:
` <IntAds name="IntAds">

    <link>
      <title>五年發展規劃</title>
      <url>http://www.cccmtl.gov.mo/promote.aspx?l=cn</url>
      <image>http://images.io.gov.mo/cn/ads/video_PDQ.gif</image>
      <source></source>
    </link> 
    <link>
      <title>訂閱《公報》電子認證版</title>
      <url>http://www.io.gov.mo/cn/subscription/</url>
      <image>http://images.io.gov.mo/cn/ads/avaebo_cn.jpg</image>
      <source></source>
    </link>
    <link>
	  <title>澳門特別行政區e書店</title>
	  <url>https://itunes.apple.com/cn/app/ao-men-te-bie-xing-zheng-que/id605274038?ls=1%26mt=8</url>
	  <image>http://images.io.gov.mo/cn/ads/MacauEBook.gif</image>
	  <source></source>
    </link>      
    <link>
      <title>訊息通知服務</title>
      <url>http://images.io.gov.mo/cn/ads/mensagem/mensagem.pdf</url>
      <image>http://images.io.gov.mo/cn/ads/mensagem/mensagem_cn.gif</image>
      <source></source>
    </link>	
    <link>
      <title>網上購書服務</title>
      <url>http://publication.cip.gov.mo/lang.aspx?language=zh-TW</url>
      <image>http://images.io.gov.mo/cn/ads/io_eshop.gif</image>
      <source></source>
    </link>

  </IntAds>`

**Comment by xiquinho** [comment]
ok, done.
