### ISSUE TITLE
BO date format

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#13]
please use **yyyy/mm/dd**(2016/05/09) for bo issue date format.

![image](https://cloud.githubusercontent.com/assets/19220046/15138799/c93a807c-16c4-11e6-97d6-fa2a37f3f020.png)

**Comment by xiquinho** [comment]
you mean leading zeros on single digit dates or what?

**Comment by bo-io-gov-mo** [comment]
yes. two digit for month and day.

**Comment by xiquinho** [comment]
ok, done.
