### ISSUE TITLE
add bo text site header

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#14]
Add header to bo text site [bo.io.gov.mo](http://bo.io.gov.mo/bo/i/2016/19/bo19_cn.asp) as same as homepage header.

![image](https://cloud.githubusercontent.com/assets/19220046/15175403/aa864fec-1798-11e6-98ad-08964fe4e991.png)

**Comment by bo-io-gov-mo** [comment]
The agency name will change to picture for display certainly.

Governo da RAEM 
 Imprensa Oficial
澳 門 特 別 行 政 區 政 府 
 印 務 局

![image](https://cloud.githubusercontent.com/assets/19220046/15175478/15349650-1799-11e6-959c-2f5b816c2a08.png)

new picture will give you soon.

**Comment by xiquinho** [comment]
I am not sure if the new header is compatible with the old design as they use totally different technologies. I cannot copy/paste this… how do you suggest add the header “as same as homepage header”?

**Comment by xiquinho** [comment]
this header is ok or not yet?

**Comment by bo-io-gov-mo** [comment]
not yet. give picture to you next week.

**Comment by bo-io-gov-mo** [comment]
The header pic here: http://betabo.io.gov.mo/A/home.htm

changed pic：logoraem.png，logoraem.svg，logoio.png，logoio.svg，titleio.png，titleio.svg。

changed code: 
 ````
<div class="col-xs-3 col-sm-2">
       <a href="http://betan.io.gov.mo/"><img class="img-responsive center-block headerlogos" alt="澳門特別行政區政府" onerror="this.src='home.files/logoraem.png'" height="65px"  src="home.files/logoraem.svg"></a>
</div>
<div class="col-xs-6 col-sm-8">
    <a href="http://betan.io.gov.mo/"><img class="img-responsive headeriotitle" alt="澳門特別行政區政府印務局" onerror="this.src='home.files/titleio.png'" height="30%" src="home.files/titleio.svg"></a>
</div>
<div class="col-xs-2 col-sm-2">
    <a href="http://betan.io.gov.mo/"><img class="img-responsive center-block headerlogos" alt="印務局" onerror="this.src='home.files/logoio.png'" height="65px"  src="home.files/logoio.svg"></a>
</div>
 ````
Jon
20/06/2016

*The top banner include include home button and search bar.

**Comment by xiquinho** [comment]
these pictures are incompatible with responsive design.

**Comment by bo-io-gov-mo** [comment]
I don't know why not incompatible, you convert it to fulfill responsive design.

**Comment by xiquinho** [comment]
I know you don't know, that is obvious. Is is not a question of conversion, if you resize the window you can see it by yourself, the text became too small and unreadable.

**Comment by xiquinho** [comment]
Also, to include the search bar I will need to change the bo.io.gov.mo template to support bootstrap, It will take time and might change the actual design.

**Comment by bo-io-gov-mo** [comment]
1. I tested it is smaller than text at mobile screen because include portuguese, I think can adjust the size or separate cn,pt pictures.
![image](https://cloud.githubusercontent.com/assets/19220046/16218068/4c2c1c5e-37ac-11e6-8e09-af01dc127cb3.png)

2. If the top banner can't put search bar at bo template, at least put a home button or icon link back to home.

**Comment by xiquinho** [comment]
1 –  Is not because include Portuguese. In your design Portuguese and Chinese are exactly the same size and both too long expressions to be readable in the same line. And I ALREADY adjust the text size and separate the pictures to optimize the logos and text display…. It is hard to understand what are you trying to achieve for “for display certainly” other than make the text unreadable.

2 – I am not saying I can’t put search bar at bo.io.gov.mo template. I can. I just need to change the template, it takes time and probably it might change the actual design. Anyway, the actual design must be changed if you want to make it responsive as the new, I just don’t have any idea about what you or your designer want or don’t want.

**Comment by bo-io-gov-mo** [comment]
1. Because use TEXT can't display font exactly what we want, and font render always different display on various browser.for example 3 different font on 3 browser:
![image](https://cloud.githubusercontent.com/assets/19220046/16218826/da291910-37b3-11e6-8509-32488e79cc6e.png)



2. For me is ok, beside: missing home icon; IO Title text; left side white margin on small screen.
![image](https://cloud.githubusercontent.com/assets/19220046/16218684/b532c1e8-37b2-11e6-8900-dee748a10cae.png)

**Comment by xiquinho** [comment]
1 – Ok, Nelson you are right and I was wrong. The image is much better; I will change it asap.

2 – Pl. send home icon in image mode. The margin on the left is from bo.io.gov.mo template. I cannot remove it on small screen because from bo.io.gov.mo template is not responsive yet and to make it responsive I will need to change the template.

**Comment by bo-io-gov-mo** [comment]
You also right, the image text is small on mobile screen, we need to fix it first.

**Comment by bo-io-gov-mo** [comment]
here is update of the site header, please replace with it.
http://betabo.io.gov.mo/B/home.htm

**Comment by xiquinho** [comment]
Can you please make the changes in the css code in your own files? Right now you are changing my own files, I cannot tell which lines you change and I cannot replace the files because meanwhile I might have made some changes on my own files.

1-	Don’t change my files unless warn me first.
2-	Create a file something.css and code all your changes there.
3-	Pl. resend this with the new and updated files only. The original files should remain untouched.
4-	Thanks a lot…

**Comment by bo-io-gov-mo** [comment]
I haven't change your css files, please show me what your own files changed.

**Comment by xiquinho** [comment]
bootstrap-extras.css is modified the problem is  I don't know which lines. Btw, congratulations for the solution found. Convert the text to a font and force the server to fetch 4 or 5 files to display a single image, is brilliant without any doubt. Keep up the good work, everyday this is improving….

**Comment by bo-io-gov-mo** [comment]
After I take a look, it is not a good solution. I only request modify the "a single image " for prevent font display small on mobile screen.

**Comment by xiquinho** [comment]
The "a single image " will always display small on mobile screen. This is web design, not book cover design…. The only way to prevent font display too small is to use TEXT (just like I did) not an image.

**Comment by bo-io-gov-mo** [comment]
This is not problem text or image, now images is show MORE text(two languages) then before!

**Comment by bo-io-gov-mo** [comment]
This is the requirement of I received! Before my idea use pic make display title more exactly in chinese! you can take a look for many other agency or company. Now, the request is much more then before, need **two language together**.

**Comment by xiquinho** [comment]
requirement from who? from SAFP???

**Comment by bo-io-gov-mo** [comment]
my boss!

**Comment by xiquinho** [comment]
Well, just explain your boss this is not a valid requirement because is impossible to achieve. Is that simple.

**Comment by bo-io-gov-mo** [comment]
Regard to bo site pages header **HOME** icon, I already ask jon make and give us soon.

![image](https://cloud.githubusercontent.com/assets/19220046/17044789/f1f40d8e-4ff5-11e6-95ea-083cc5c19456.png)

**Comment by bo-io-gov-mo** [comment]
home icon here: [home.zip](https://github.com/bo-io-gov-mo/website/files/377704/home.zip)

**Comment by xiquinho** [comment]
this is to put where exactly? BO pages, new website or both?

**Comment by xiquinho** [comment]
what about the size? do I resize or keep the original size?

**Comment by bo-io-gov-mo** [comment]
In ideal, site header is expect same everywhere, you told me BO old template pages cannot make as same as betan. Then you make it similar as homepage, for me is ok.

**Comment by xiquinho** [comment]
I am not talking about the site header, I am talking about the icon.

I don't have any idea about what you want to do regarding the site header. You told me before Jon will send an image and I am still waiting.

**Comment by bo-io-gov-mo** [comment]
Yes, I ask jon make it and send to you soon.

**Comment by xiquinho** [comment]
so, what about the **icon** size? do I resize the **icon** or keep the **icon** original size?

**Comment by bo-io-gov-mo** [comment]
it only use on bo site and the size same as homepage. please resize it if not suitable.

**Comment by xiquinho** [comment]
done, pl. check.

**Comment by bo-io-gov-mo** [comment]
regard to site header of imprensa text, i got it just now:
[io_text_png.zip](https://github.com/bo-io-gov-mo/website/files/405913/io_text_png.zip)

**Comment by xiquinho** [comment]
done at
http://betan.io.gov.mo/cn/home/

pl confirm before I change the remaining places.

**Comment by xiquinho** [comment]
done again with Jon files update at:

http://betan.io.gov.mo/cn/home/

pl confirm before I change the other places. (search and BO)

**Comment by xiquinho** [comment]
reminder: pl confirm before I change the other places. (search and BO)

**Comment by bo-io-gov-mo** [comment]
I ask others to confirm, the feedback is basically fine. It is ok. Unless we only find a bug on WIN7+IE display it on small size screen, the title picture not zoom out as others.

**Comment by xiquinho** [comment]
so, can I optimize this and replicate on the other places? Yes or No?

**Comment by bo-io-gov-mo** [comment]
Yes. It is ok.

**Comment by xiquinho** [comment]
do you know why the mobile pages are not displaying in beta like in production, ex:

http://betabo.io.gov.mo/bo/i/95/06/bo06.asp?mobile=1

http://bo.io.gov.mo/bo/i/95/06/bo06.asp?mobile=1

are different, why?

**Comment by bo-io-gov-mo** [comment]
it show fail to load resource on server, you can use chrome debug console. pls take a look.

**Comment by xiquinho** [comment]
it looks like is missing a folder 'mob' but I don't know why, when or who delete it. It was written by Danda, not me.

**Comment by xiquinho** [comment]
btw, bo text site bo.io.gov.mo is now as same as homepage and search header, pl. check.

**Comment by bo-io-gov-mo** [comment]
1. click the home button appear problem.
2. hide the search bar.

**Comment by xiquinho** [comment]
done
