### ISSUE TITLE
施政報告 Relatório das Linhas de Acção Governativa not full complete

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#15]
I will give you those doc before 2006 later. finding now.

![image](https://cloud.githubusercontent.com/assets/19220046/15175742/5960e63e-179a-11e6-8b6e-28da66086d13.png)

**Comment by xiquinho** [comment]
until which year?

**Comment by xiquinho** [comment]
ok done, until 2000, just upload the files using the same names/structure.

**Comment by bo-io-gov-mo** [comment]
noted.

**Comment by bo-io-gov-mo** [comment]
please cancel year 2000 link tile, others we already upload the files.

**Comment by xiquinho** [comment]
ok.
