### ISSUE TITLE
Legislation filter/search

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#16]
Dear Nelson,

These pages are provisional and will disappear once the search is build.

It is not build yet because is impossible to finish it before next month, but I will once I came back.

Better you explain me personally what you want because what you write is not clear. What filter function? What search function to optimize the search??

Rgds

FN

From: nelson@io.gov.mo [mailto:nelson@io.gov.mo] 
Sent: Monday, March 21, 2016 12:08
To: 'FN' <fnunes@io.gov.mo>
Subject: 回覆: legislation filter

Dear Fernando,

          These pages need build filters however search have same filter or not soon. This is separate filter function and search function to optimize the search.

Thanks,
Nelson Chan

寄件者: FN [mailto:fnunes@io.gov.mo] 
寄件日期: 2016年3月21日 11:45
收件者: nelson@io.gov.mo
主旨: RE: legislation filter

Dear Nelson,

I already told you before this page is provisional and all the filters will be included on the search page once is finished. 

There is no need to waste time in duplicating the resources, ie build 2 search pages, one with all the filters and other with only 2 filters.

The records per page are 150 you can change it if you want.

Rgds
FN

From: nelson@io.gov.mo [mailto:nelson@io.gov.mo] 
Sent: Monday, March 21, 2016 11:21
To: 'FN' <fnunes@io.gov.mo>
Subject: legislation filter

Dear Fernando,

          The following thing forget to told you last week, but I’ve talk this before. And how many record show on one page, it seem to many now.

![l_filter](https://cloud.githubusercontent.com/assets/19220046/15207529/5ec67430-1859-11e6-90ab-ed60b1b18216.jpg)

Thanks,
Nelson Chan

**Comment by xiquinho** [comment]
As I explain before, this page was provisional while the new search was not working. It is now and you will find all the required filters there without need to duplicate it.

**Comment by bo-io-gov-mo** [comment]
I don't need all filter, for example when i go inside lei, don't show "Tipo de Diploma" filter, my means filter need customize for different page.

**Comment by bo-io-gov-mo** [comment]
Please put keyword search and two filter into Legislação every tile. for example like:
http://betan.io.gov.mo/cn/legis/list/a/48
![image](https://cloud.githubusercontent.com/assets/19220046/16757413/6e2ab700-483e-11e6-8aa7-4476d00ea8b4.png)

put the keyword search and year filter into Notícias:
http://betan.io.gov.mo/cn/news
![image](https://cloud.githubusercontent.com/assets/19220046/16757558/6f1a6fc4-483f-11e6-9076-a5d4b638cdef.png)

**Comment by xiquinho** [comment]
done, pl. check.

**Comment by bo-io-gov-mo** [comment]
not yet.

**Comment by xiquinho** [comment]
what do you mean "not yet"?

**Comment by bo-io-gov-mo** [comment]
it can see now, thanks. I'm going to test it.

**Comment by bo-io-gov-mo** [comment]
sorry, it is not I expect. We want some filter and show the result within category pages, not link to search page. We want separate search and filter function, not mess together.

**Comment by xiquinho** [comment]
I told you since the beginning these pages are provisional and will disappear when the search is finish just like in the original design. do you want to link directly? It doesn't make sense to build 2 search pages to search the same thing.

**Comment by bo-io-gov-mo** [comment]
As beginning of the web design is separate category filter and search. So I hope these pages is not provisional at all. It is correct and put number and year filter inside it. But the keyword search is request recently, and it may be not good appear.

**Comment by xiquinho** [comment]
no you are wrong: the original design links directly for search page. check the design Jon sent to me. These pages I build myself only for provisional, You sure don't expect to develop, test and maintain 3 search pages x 2 languages, total 6 pages, to do the same thing?

**Comment by xiquinho** [comment]
Actually, at this time the search page already supports the all the filters and this lists can be replaced. Pl. check now the result as the original design Jon sent to me and the director approved.

**Comment by bo-io-gov-mo** [comment]
I want to clarify, the original design of jon is link back to search pages, because no other category pages can link to represent result at that time, you can ask him to confirm. I know separate category and search cause more pages to develop and maintain, but it is more clearly to present data worthy. It is specific to some kind of people use scenario which is different from search keyword. 
Finally, two filter category pages is more simply than search page. You already implement a most difficult one, it is very nice.  If you can't not add keyword search to those pages, I hope you can add number and year filter to exist category pages. It is not request only my personally.

**Comment by xiquinho** [comment]
It is not a question of what I can but a question you don’t know what you want. First you want a filter with number and year, after that you want number, year and keyword and now that you want only number and year again and all the time you don’t understand these pages are the same page. The “category pages” don’t exist on the original design, don’t exist in the original website, don’t exist anywhere. 

It is the same page, the same results, the same search page, only difference is the missing form with the  number, year and keyword fields because you told me last year you need the website ready before the 18 months expire. And I create these pages with fixed results only to display something until the search is ready. And now you want 3 different searches, one for each page? Doing all the same, giving all the same results? This is a total nonsense and a waste of time and resources…

**Comment by xiquinho** [comment]
It is neither a question of “cause more pages to develop and maintain”
I don’t care with more or less pages, it is my job and I am not complaining about it. But it is a question 3 pages doing the same thing it is only a question of time they start to give different results. The search page is becoming complex and it is very hard to replicate this complexity in many different places. If later I update something in one page and forget to update in the others how will you explain later different results in the same searches? Obviously, you can’t.

**Comment by xiquinho** [comment]
done, pl. check.

**Comment by bo-io-gov-mo** [comment]
![image](https://cloud.githubusercontent.com/assets/19220046/17544772/e232f70a-5f0b-11e6-8f16-8f8fff5c9df3.png)


**please replace the first one with:**
![image](https://cloud.githubusercontent.com/assets/19220046/17544797/02bf6c92-5f0c-11e6-8102-d6b7caae7f28.png)
