### ISSUE TITLE
Add tab broder line of public entity

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#18]
please add tab broder line when first into public entity:
http://betan.io.gov.mo/cn/entities/admpub/rec/10000
![image](https://cloud.githubusercontent.com/assets/19220046/15464338/43c97938-2101-11e6-9418-d3085bed3445.png)

![image](https://cloud.githubusercontent.com/assets/19220046/15464389/93c6675c-2101-11e6-88af-5bd1e409fa12.png)

**Comment by xiquinho** [comment]
ok.
