### ISSUE TITLE
add a chinese space before 法例

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#19]
please add a chinese fullwidth space before  法例 menu. only on chinsese version.
![image](https://cloud.githubusercontent.com/assets/19220046/15490818/fbb679dc-219d-11e6-9348-d5021ba896a7.png)

![image](https://cloud.githubusercontent.com/assets/19220046/15490867/1bdf9734-219e-11e6-8035-a3e5bc248d3a.png)

**Comment by xiquinho** [comment]
can you send me an example of "chinese fullwidth space" please?

**Comment by bo-io-gov-mo** [comment]
here (only clever man can see:)＂　＂

**Comment by xiquinho** [comment]
ok.

**Comment by xiquinho** [comment]
can you see it now?

**Comment by bo-io-gov-mo** [comment]
Yes
