### ISSUE TITLE
add header bo No., serie on Extractos de despachos & Avisos e anúncios oficiais 批示摘錄&政府機關通告及公告

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#20]
add header: bo No.,serie,date... to Extractos de despachos & Avisos e anúncios oficiais.

for example bo no20. sumario:
http://bo.io.gov.mo/bo/ii/2016/20/bo20.asp
![image](https://cloud.githubusercontent.com/assets/19220046/15494390/b73765cc-21bc-11e6-9e55-f129a348d345.png)

http://bo.io.gov.mo/bo/ii/2016/20/extractos_cn.asp
![image](https://cloud.githubusercontent.com/assets/19220046/15494443/081993e8-21bd-11e6-9398-e2b671eed58c.png)

http://bo.io.gov.mo/bo/ii/2016/20/avisosoficiais_cn.asp
![image](https://cloud.githubusercontent.com/assets/19220046/15494462/1d8dcfe6-21bd-11e6-8410-d89b0c6fbc48.png)

**Comment by xiquinho** [comment]
this is urgent?

**Comment by bo-io-gov-mo** [comment]
I think not urgent. This request I heard long time ago, and someone fill online survey talk about this this year.

**Comment by xiquinho** [comment]
I still need to finish the International Law and the search, better you tell me what you want first.
Beside there are a few old pages (from year 2000, I think) with the old template which don’t support this and the new logo.

**Comment by bo-io-gov-mo** [comment]
YES! You go ahead International Law and the search first. It is most urgent.

**Comment by xiquinho** [comment]
I am working on these. Meanwhile, you can ask Jon or Cat to replace the pages with the new template, from years 2000 until 2003, for example:
http://betabo.io.gov.mo/bo/ii/2000/01/avisosoficiais.asp
only the new template supports the new logo.

**Comment by bo-io-gov-mo** [comment]
ok, I try to understand and ask them progress first.

**Comment by bo-io-gov-mo** [comment]
Jon already finished replace the pages from years 2000 until 2003, please check it.

**Comment by xiquinho** [comment]
the sumario pages are still using the old template, for example:

http://betabo.io.gov.mo/bo/ii/2000/01/bo01.asp
http://betabo.io.gov.mo/bo/ii/2000/01/bo01_cn.asp

Where is:








should be:





and:





should be:



The ideal would be to remove all FrontPage references not only until 2003 but from all the files, otherwise sooner or later we will have problem with this.

In my opinion all files should be upgraded to 2016 template for everything remain consistent.

**Comment by xiquinho** [comment]
btw, I don’t think it is very wise let anyone on read these comments some of them, including private urls which are not intended for the public view. Can you please change the privacy settings for these conversations?

**Comment by bo-io-gov-mo** [comment]
1.Is it must be change? or put it later. Our purpose can display title banner first. Because change lot of previous pages may be cause mistake and not enough to check it all. 

2.how to change conversation privacy setting?

**Comment by xiquinho** [comment]
1 - It depends on the banner. My idea was to make bo pages fully responsive with bootstrap and for that all need to use the same template. But if you are happy with the banner as it is now, it could be later.

2- I don’t know but I think these conversations should not be available to the public, and right now they are. Try this url with an anonymous account and you will see:

https://github.com/bo-io-gov-mo/website/issues/20#issuecomment-226083902

**Comment by xiquinho** [comment]
done, pl. check.
