### ISSUE TITLE
homepage right banner

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#21]
HomePage right banner (not urgent)
![image](https://cloud.githubusercontent.com/assets/19220046/15526466/ddac93fa-2264-11e6-9abf-ef82b9bdea68.png)

**Comment by xiquinho** [comment]
what is the problem?

**Comment by bo-io-gov-mo** [comment]
will add one more banner and renew another one, these picture will give you later. I noted it first for prevent forget.

**Comment by xiquinho** [comment]
any new banner and renew another one?

**Comment by bo-io-gov-mo** [comment]
Already add DipOrder field to vwIndexQuery view. A, B and C table is ok, but DintDocList table can't find it, I put it zero.

 Others, When I take a look into DintDocList union query, I found below condition at the end: 
``
... AND Dint_DocList_DocLang_join.LangID = 22
``
I don't know is it correct?

````
...
UNION ALL
SELECT     DintDocList.tboID AS id, 'D' AS cat, DocName_pt AS DiplomNamept, DocDesc_pt AS DiplomDescpt, DocName_pt + DocDesc_pt AS Textpt, 
                      DocName_cn AS DiplomNamecn, DocDesc_cn AS DiplomDesccn, DocName_cn + DocDesc_cn AS Textcn, DintDocList.LinkID, DocDate AS DatePublished, 
                      '0' AS DiplomUrl, BONumber, BOYear, Serie, suplemento, 600 AS Diplomlvl, DintDocList.PID, DintDocList.PIDOriginal, 'Direito Internacional' AS CatNamePT, 
                      N'國際法' AS CatNameCN, 
                      0 AS typeID, 0 as DipOrder
FROM         DintDocList INNER JOIN
                      Dint_DocList_DocLang_join ON DintDocList.LinkID = Dint_DocList_DocLang_join.LinkID INNER JOIN
                      tbo2004 ON Dint_DocList_DocLang_join.LinkIDtbo2004 = tbo2004.LinkID
WHERE     tbo2004.Active = 1 AND MSAR = 1 AND Dint_DocList_DocLang_join.LangID = 22

````

**Comment by bo-io-gov-mo** [comment]
![image](https://cloud.githubusercontent.com/assets/19220046/17545784/4a9b0c92-5f11-11e6-9555-5a01c890af83.png)

please replace the first banner with below one:
![image](https://cloud.githubusercontent.com/assets/19220046/17545761/2700cd58-5f11-11e6-9128-a4ce9face3f5.png)

**Comment by xiquinho** [comment]
and PT?

**Comment by bo-io-gov-mo** [comment]
yes. it is as same as existing website.

**Comment by xiquinho** [comment]
done, pl check.

**Comment by bo-io-gov-mo** [comment]
pls open another window to show it.
