### ISSUE TITLE
Legis duplicated

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#22]
http://betan.io.gov.mo/cn/legis
![image](https://cloud.githubusercontent.com/assets/19220046/15737809/af80dcbc-28da-11e6-8b04-e14f947c919b.png)

http://betan.io.gov.mo/pt/legis
![image](https://cloud.githubusercontent.com/assets/19220046/15738157/941096d2-28dc-11e6-8bd5-997077c1dff8.png)

**Comment by xiquinho** [comment]
ok
