### ISSUE TITLE
Legis change title  "規章"

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#23]
Chinese title change to "規章"

http://betan.io.gov.mo/cn/legis/
![image](https://cloud.githubusercontent.com/assets/19220046/15737880/153b01a4-28db-11e6-890d-6033ca989c34.png)

http://betan.io.gov.mo/cn/legis/list/a/61
![image](https://cloud.githubusercontent.com/assets/19220046/15737910/42f47792-28db-11e6-8e61-a9e4167b569c.png)

**Comment by xiquinho** [comment]
ok
