### ISSUE TITLE
Remove or make "Códigos" under "Legislação" directly

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#24]
Remove or make "Códigos" under "Legislação" directly.
 
http://betan.io.gov.mo/cn/legis/rec/2200
![image](https://cloud.githubusercontent.com/assets/19220046/15738013/c9ab66b0-28db-11e6-8b31-72c9630f0b32.png)

http://betan.io.gov.mo/pt/legis/rec/2200
![image](https://cloud.githubusercontent.com/assets/19220046/15738063/03665b58-28dc-11e6-87f7-f37a069f8fbd.png)

**Comment by xiquinho** [comment]
ok for next time db updates
