### ISSUE TITLE
update home page BO list icon

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#25]
please update the bo list icon of homepage. here attach the sample.
[BO_List.zip](https://github.com/bo-io-gov-mo/website/files/334389/BO_List.zip)

**Comment by bo-io-gov-mo** [comment]
please update the img use svg first.
````
<img src="images/bo_i_cn.svg" onerror="this.src='images/bo_i_cn.png'" />
   ````
````
<img src="images/bo_i_pt.svg" onerror="this.src='images/bo_i_pt.png'">````

**Comment by xiquinho** [comment]
It doesn't look very safe, what is the advantage of this?

**Comment by bo-io-gov-mo** [comment]
agree! but svg more clearly on any display size of image. now is not.

**Comment by xiquinho** [comment]
png or svg the image doesn’t read clearly either format as is impossible to shrink BO cover to this size and expect it to be clear. Clearly is not. The only thing clear here is whoever design this don’t have any idea about the concept of design, let alone web design. It breaks all the rules, even the most elementary.

**Comment by xiquinho** [comment]
done, will be visible tomorrow.
