### ISSUE TITLE
Search issue report 2

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#26]
#8 Let start a new discuss for search function, I write down my requirement.

I expect search result include descricao, bono, date. as existing table format.
![image](https://cloud.githubusercontent.com/assets/19220046/16513867/a6996cdc-3f9a-11e6-9d04-fee3d2800b51.png)

**Comment by xiquinho** [comment]
OK, but you told me you want a “like Google” thing… a table format is not a a “like Google” thing.

**Comment by xiquinho** [comment]
sorry is not clear do you want the table or not?

**Comment by bo-io-gov-mo** [comment]
I know you understand my opinion, I want to set up 3 basic rule for search user behaviour offer:
1. search ALL content, include A/B/C or AB/C table in tab.
2. filter AFTER search, show the filter items that only include result.
3. search suggestion, assist user to complete the keyword.
I think above change should enhance search user experiment.

Inside: 
1. We optimize result TITLE first sort order. 
2. Customize chinese word breaker, we define our custom dictionary.
3. Set synonyms for common word or phrase. (no good solution yet)

**Regard the result layout, I reply you later.**

**Comment by xiquinho** [comment]
sorry, I only understand 3. Better you explain personally what you want for 1 and 2.

**Comment by bo-io-gov-mo** [comment]
please check follow case:
----------

betabo
[澳門金融管理局](http://cn.io.gov.mo/BO/B/Link/3916.aspx), 通告一則，公佈獲准在澳門特別行政區從事保險中介人的名單

bo
[澳門金融管理局](http://betacn.io.gov.mo/BO/B/Link/3916.aspx), 通告一則，公佈獲准在澳門特別行政區從事保險中介人的名單

----------

▪ 第799號立法性法規, 飭將郵電專理局僱工日工散工三種人員編制的名額更正。　
http://cn.io.gov.mo/Search/default.aspx?t=A&q=799&s=r&o=And&sc=f

http://betan.io.gov.mo/cn/search?q=799

**Comment by xiquinho** [comment]
I am using these packages pl.check if  u r using the same versions

..\packages\jieba.NET.0.37.1\lib\net45\JiebaNet.Analyser.dll
and
..\packages\jieba.NET.0.37.1\lib\net45\JiebaNet.Segmenter.dll

**Comment by xiquinho** [comment]
that is a bug, need to remove the link on the records without text. I will fix it asap.

**Comment by xiquinho** [comment]
I am using these packages pl.check if u r using the same versions

..\packages\jieba.NET.0.37.1\lib\net45\JiebaNet.Analyser.dll
 and
 ..\packages\jieba.NET.0.37.1\lib\net45\JiebaNet.Segmenter.dll

**Comment by xiquinho** [comment]
the link problem is fixed, but meanwhile I found the first result do not appear on the PT version, not sure why.

**Comment by xiquinho** [comment]
can you send me the url of the other search with the filters for I take a look? It was on the other search thread that is now closed.

**Comment by bo-io-gov-mo** [comment]
try here: http://192.168.3.22/iosearch3

**Comment by bo-io-gov-mo** [comment]
above link password same as username

**Comment by xiquinho** [comment]
ty, can you add the portuguese after or below the chinese filter? 

I am a little bit lost on the meaning of the filters....

**Comment by bo-io-gov-mo** [comment]
sorry for confusing you about the filters, above link is AFTER search filter example for show the concept. We can discuss and customize how to show the filters on production. All the filters not over your existing have.

**Comment by xiquinho** [comment]
Ok, just let me know exactly which filters you want over the existing or something else.

**Comment by bo-io-gov-mo** [comment]
In above site filters, I choose "Document Type" for A record
![image](https://cloud.githubusercontent.com/assets/19220046/16607476/f04231ca-4373-11e6-817b-d0ce2e7803f5.png)

Public Entities for B record
![image](https://cloud.githubusercontent.com/assets/19220046/16607486/0cb68afe-4374-11e6-8879-f6d0c1f18be7.png)

And static fixed "Private Notices and Others" for C record and "International Law" for DintDocList record.
![image](https://cloud.githubusercontent.com/assets/19220046/16607553/cbff4702-4374-11e6-97f3-ce6b0fd39071.png)

It is not enough and fine, for example missing: years, boNo...., depend how you design.

**Comment by xiquinho** [comment]
OK, let’s start with "Document Type" for A record. 

I am trying to find an efficient way to display this filter for any given search, but so far nothing good comes to my mind. Can you show me how did you build the sql queries on your demo to filter this?

**Comment by bo-io-gov-mo** [comment]
Behind the demo is Solr search engine build in function, those is a powerful search engine. Regard to sql server, we try to create a store procedure to return both table, catName and search result for you display.

**Comment by xiquinho** [comment]
Ok, but how do you query Solr search engine database to retrieve the results, the filters and the number of records all together? I can create the same procedure for sql server, I just don’t know how to build it efficiently. If I saw the solr sql query perhaps I could make it better for sql server.

**Comment by bo-io-gov-mo** [comment]
IOSearchQuery view for solr retrieve data:
````
SELECT     'A-' + CONVERT(nvarchar(50), FT_TBL.tboID) AS id, 'A' AS cat, FT_TBL.DiplomNamept, FT_TBL.DiplomDescpt, FT_TBL.Textpt, FT_TBL.DiplomNamecn, 
                      FT_TBL.DiplomDesccn, FT_TBL.Textcn, FT_TBL.DiplomNameen, FT_TBL.DiplomDescen, FT_TBL.Texten, FT_TBL.Descritorespt, FT_TBL.Descritorescn, 
                      FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.suplemento, DiplomTypes.Diplomlvl, 
                      DiplomTypes.DiplomNamept AS CatNamePT, DiplomTypes.DiplomNamecn AS CatNameCN, DiplomTypes.DiplomNameen AS CatNameEN, NULL AS CatParent
FROM         tbo2004 AS FT_TBL LEFT JOIN
                      DiplomTypes ON FT_TBL.DiplomCode = DiplomTypes.DiplomCode
WHERE     FT_TBL.active = 1
UNION ALL
SELECT     'B-' + CONVERT(nvarchar(50), FT_TBL.tboID) AS id, 'B' AS cat, FT_TBL.DiplomNamept, FT_TBL.DiplomDescpt, FT_TBL.Textpt, FT_TBL.DiplomNamecn, 
                      FT_TBL.DiplomDesccn, FT_TBL.Textcn, FT_TBL.DiplomNameen, FT_TBL.DiplomDescen, FT_TBL.Texten, NULL AS Descritorespt, NULL AS Descritorescn, 
                      FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.suplemento, DiplomTypes.Diplomlvl, 
                      Category.CatName_pt AS CatNamePT, Category.CatName_cn AS CatNameCN, Category.CatName_en AS CatNameEN, CatParent
FROM         tbo20002s AS FT_TBL LEFT JOIN
                      Category ON FT_TBL.CatId = Category.CatId LEFT JOIN
                      DiplomTypes ON FT_TBL.DiplomCode = DiplomTypes.DiplomCode
WHERE     FT_TBL.active = 1
UNION ALL
SELECT     'C-' + CONVERT(nvarchar(50), tboID) AS id, 'C' AS cat, DiplomNamept, DiplomDescpt, Textpt, DiplomNamecn, DiplomDesccn, Textcn, DiplomNameen, DiplomDescen, 
                      Texten, NULL AS Descritorespt, NULL AS Descritorescn, LinkID, DatePublished, DiplomUrl, BONumber, BOYear, Serie, suplemento, 1 AS Diplomlvl, NULL 
                      AS CatNamePT, N'公證書及其他公告' AS CatNameCN, NULL AS CatNameEN, NULL AS CatParent
FROM         tboanotariais
WHERE     active = 1
UNION ALL
SELECT     'D-' + CONVERT(nvarchar(50), DintDocList.tboID) AS id, 'D' AS cat, DocName_pt AS DiplomNamept, DocDesc_pt AS DiplomDescpt, 
                      DocName_pt + DocDesc_pt AS Textpt, DocName_cn AS DiplomNamecn, DocDesc_cn AS DiplomDesccn, DocName_cn + DocDesc_cn AS Textcn, 
                      DocName_en AS DiplomNamecn, DocDesc_en AS DiplomDesccn, DocName_en + DocDesc_cn AS Texten, DocName_pt + ' ' + DocDesc_pt AS Descritorespt, 
                      DocName_cn + ' ' + DocDesc_cn AS Descritorescn, DintDocList.LinkID, DocDate AS DatePublished, '0' AS DiplomUrl, BONumber, BOYear, Serie, suplemento, 
                      600 AS Diplomlvl, NULL AS CatNamePT, N'國際法' AS CatNameCN, NULL AS CatNameEN, NULL AS CatParent
FROM         DintDocList INNER JOIN
                      Dint_DocList_DocLang_join ON DintDocList.LinkID = Dint_DocList_DocLang_join.LinkID INNER JOIN
                      tbo2004 ON Dint_DocList_DocLang_join.LinkIDtbo2004 = tbo2004.LinkID
WHERE     tbo2004.Active = 1 AND MSAR = 1 AND Dint_DocList_DocLang_join.LangID = 22
````

**Comment by bo-io-gov-mo** [comment]
Solr request filters and result records two times, but it is very fast. I think sql server need use store procedure and ram table to retrieve it one time for efficiently.

**Comment by xiquinho** [comment]
The query above returns all the records including a join for the category only. But it doesn’t return the DISTINCT categories and the number of the records on each category. And this is precisely what I trying to resolve. How to find the number of records on each category so fast? Unless I calculate it one category by one, which will make the search very slow, I don’t know how. So, where is the rest of your solution? How do you find the DISTINCT categories and the number of the records in each category so fast?

**Comment by bo-io-gov-mo** [comment]
try: 
select category, count(*) from result_table group by category

**Comment by xiquinho** [comment]
ok, I will give it a try.

**Comment by bo-io-gov-mo** [comment]
we already create a store procedure call "GetFilteredTable" at control\bo2004_search for demo here: http://search2015.io.gov.mo/Search/?q=fernando&s=r&t=c&i=s

**Comment by xiquinho** [comment]
This is nice but so far I don’t understand how are you going to filter/count the records if they have multiple categories. For example, between table B and table Categories there are only 1 to 1 relationships, this is ok.  Between table A and table DiplomTypes there are only 1 to 1 relationships, this is also ok. But between table A B and table Categories there are countless 1 to many relationships. And in this case it won’t work. If tomorrow a user or your boss request another filter for table A/Categories what are you going to do?

**Comment by bo-io-gov-mo** [comment]
It should be need more complex join category from search_result table to retrieve. 
Others, the follow site is the result and filter layout what i want like this:

http://epub.cnki.net/kns/brief/default_result.aspx
![image](https://cloud.githubusercontent.com/assets/19220046/16679896/ca5eaa14-451d-11e6-8b1c-b7041809fd5c.png)

does it more suitable for us?

**Comment by xiquinho** [comment]
Everything is suitable, before you told me you want the results Google style but this don’t look nothing Google Style. Just let me know what do you want, Google style, filter style, whatever style, I will try my best to style it on your style…

**Comment by xiquinho** [comment]
Can you send me the code to display the filter tables on search2015? I will try to adapt it instead of rewrite everything again.

**Comment by bo-io-gov-mo** [comment]
If ok, we can make like this. I need to confirm again and reply you soon.

all code in TFS, can you access it?
http://192.168.3.22:8080/tfs/DefaultCollection/_git/betas?_a=history
login by your eImprensa account.

**Comment by xiquinho** [comment]
confirm what? with your boss?

**Comment by bo-io-gov-mo** [comment]
sure.

**Comment by xiquinho** [comment]
Do you want the filters on all tabs or only on the first tab?

**Comment by xiquinho** [comment]
I am asking because I am using vwIndexQuery view only in the first tab. On the other tabs I am using the original tables. But the code, stored procedure, etc you send to me only works with vwIndexQuery view, so I have here a problem...

**Comment by bo-io-gov-mo** [comment]
try this sp_executesql:
https://msdn.microsoft.com/en-us/library/ms188001.aspx
or
https://msdn.microsoft.com/library/ms188332(SQL.130).aspx

**Comment by xiquinho** [comment]
Sorry, I don’t understand, would mind to explain this:

“try this sp_executesql:”

To fix what? What I want to know is do you want the filters on all tabs or only on the first tab? Because your solution only works on the first tab. If you want to include filters on the other tabs the approach needs to be completely diferent and both codes need to change, my code and the stored procedure. So, 

“try this sp_executesql:”

Try what exactly? To achieve what?

**Comment by bo-io-gov-mo** [comment]
You said cannot make sql dynamic create filter of your sql query last week! this is the solution for you reference. Achieve what: achieve the search result filter that what we done recently, it is for demo, need you implement it to production. Anyway, If your code cannot modify for this function, we focus on first tab first. Because first tab include all record, so A, B or C such as a case of filter.

**Comment by xiquinho** [comment]
I am still studying the code Samuel is using at search2015 and how it compares with the code I am using at betan and I am not sure if I will need to use the stored procedure to filter the results or not. But first of all I will need to re-write the sql queries to support the categories and at this point I think the stored procedures are unnecessary, but I will let you know.

**Comment by bo-io-gov-mo** [comment]
Noted and thanks. I use store procedure primary consider is performance and efficient, it done data process everything in mssql server with ram table, then return a page result record and categories result for display only. It can simplify your code also. This only my opinion.

**Comment by xiquinho** [comment]
Just to clarify, my concern with performance was only if you want to include filters for records with 1 to many relationships. (for example 第238/2016號行政長官批示 have 3 categories 澳門公職法律制度 - 公共行政 - 行政公職局 ) but since your filters are using only record with 1 to 1 relationships (for example 第238/2016號行政長官批示 have 1 category 行政長官批示 ) I don’t foresee any performance problems, hence the stored procedure maybe is unnecessary. But I will let you know later asap.

**Comment by xiquinho** [comment]
Do you want to display the new filters:

a) Only when the user type a keyword
b) When the user type a keyword or another select any other dropdown filter
c) Always

**Comment by xiquinho** [comment]
pl. send the expression to replace BO on first tab

**Comment by bo-io-gov-mo** [comment]
全部

**Comment by xiquinho** [comment]
ty, pl. confirm if this is what you want:
http://betan.io.gov.mo/cn/search?q=

**Comment by bo-io-gov-mo** [comment]
can emphasize the search bar like this:
http://epub.cnki.net/kns/default.htm
![image](https://cloud.githubusercontent.com/assets/19220046/16754649/09728020-4827-11e6-9dac-99eacbd15f19.png)

sorry, I missing told you need keep this item:
![image](https://cloud.githubusercontent.com/assets/19220046/16754678/7d0c44bc-4827-11e6-8641-51e55b294959.png)

**Comment by bo-io-gov-mo** [comment]
and put it in front of search bar.

**Comment by xiquinho** [comment]
what is the item missing to put in front of the search bar?

**Comment by bo-io-gov-mo** [comment]
above combo box: "Texto / Título e descrição"

**Comment by xiquinho** [comment]
Can't skip this? I am not sure how to re-write the SQL Query for the first tab. I just copy/paste the text you gave me...

**Comment by bo-io-gov-mo** [comment]
I think it is important, but without text_cn sql query is more simply, it is very similar your existing search logic. if amend my query like this:
````
WITH result_set AS 
(SELECT ROW_NUMBER() OVER (ORDER BY title_Rank DESC, DatePublished DESC) AS [row_number], TBL_Display.LinkID, TBL_Display.Tab , TBL_Display.DipName, TBL_Display.DipDesc, TBL_Display.DatePublished, TBL_Display.DiplomUrl, TBL_Display.BONumber, TBL_Display.BOYear, TBL_Display.Serie, TBL_Display.suplemento,  TBL_Display.diplomlvl, TBL_Display.org_title_Rank, TBL_Display.title_Rank as rank FROM (SELECT FT_TBL.LinkID, FT_TBL.CAT AS Tab,FT_TBL.DiplomNamecn AS DipName,FT_TBL.DiplomDesccn AS DipDesc,FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.suplemento , Title_Rank as org_title_Rank,(tbl_rank.title_Rank+isNull(FT_TBL.diplomlvl,0)*100) AS title_Rank, FT_TBL.diplomlvl,FT_TBL.DatePublished
 FROM vwIndexQuery AS FT_TBL INNER JOIN 
(
 SELECT t.Title_Rank AS Title_RANK, s.tboID,s.LinkID,s.tab FROM (SELECT [KEY], Rank as Title_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033))as t inner join Search as s on t.[key]=s.tboID
)
AS TBL_Rank on (FT_TBL.LinkID=TBL_Rank.LinkID and FT_TBL.cat=TBL_Rank.tab)) AS TBL_Display
) SELECT * FROM result_set WHERE [row_number] BETWEEN 0 AND 24
 ````

**Comment by xiquinho** [comment]
In my query is easy, I can choose which fields to search programmatically. But your query is very confused (to me…) because the fields are separated with a UNION ALL and included in the RANK calculations…

So, what I need is:

a) A sample sql query for text only
b) A sample sql query for title and description only.

Can you send it?

**Comment by bo-io-gov-mo** [comment]
a. search2015 sql is full content(title and text).
b. above sql is title(include: name & description) only.
No any require text only.

**Comment by xiquinho** [comment]
ok, got it now.

**Comment by bo-io-gov-mo** [comment]
On the right side result filters, please add a header to each filter, can collaps or scroll items like:
http://test.eimprensa.net/iosearch3 

thanks a lot!

**Comment by xiquinho** [comment]
http://test.eimprensa.net/iosearch3 = Not Found

**Comment by bo-io-gov-mo** [comment]
After discuss with my boss, we want the search layout like:
http://192.168.3.22/iosearch3

1. hide left menu at search page.
2. put result filter to left side.
3. display style/format/color similar.

**Comment by bo-io-gov-mo** [comment]
similar layout reference:
http://s.g.wanfangdata.com.hk/Paper.aspx?q=macau

http://www.airitilibrary.com/Search/ArticleSearch?ArticlesViewModel_SearchField=macau

**Comment by xiquinho** [comment]
Sure, everyday improving! It is not clear if you want to keep the old filters or not, can you please clarify?

**Comment by bo-io-gov-mo** [comment]
I want to clarify that result filters only display those filters which HAVE result. for example: I search "peter", only show filters include peter, not show all filters.
http://search2015.io.gov.mo/Search/?q=peter&s=r&t=c&i=s

**Comment by xiquinho** [comment]
yes, I understood that but I didn't finish my filters yet. right now is displaying all filters but later will display filters only with results.

**Comment by bo-io-gov-mo** [comment]
please add me to your tfs project or clone the project to me. I want to try different layout display result. If need change something later, that easy give you to integrate. My Microsoft account: nelson@io.gov.mo

**Comment by xiquinho** [comment]
pl. make your changes under betawww2016test, don't change the other without warning me.

**Comment by bo-io-gov-mo** [comment]
I want clone the project, but nothing inside i can see, please check you authorize setting.

**Comment by xiquinho** [comment]
Can't you open it on VS?

**Comment by bo-io-gov-mo** [comment]
now is ok, slow opening. thanks.

**Comment by xiquinho** [comment]
first time takes long time but after that it will be fine.

**Comment by xiquinho** [comment]
please confirm the top filters and the layout. Is this what you want or not?

**Comment by xiquinho** [comment]
please take a look on Tab A and filters and let me know if this what you want or not.

**Comment by bo-io-gov-mo** [comment]
search bar ref:
http://bootsnipp.com/snippets/featured/search-panel-with-filters
http://bootsnipp.com/snippets/e33Wv
http://bootsnipp.com/snippets/88P5
http://bootsnipp.com/snippets/eN0Pv

http://bootsnipp.com/snippets/40Bqx

**Comment by xiquinho** [comment]
great thans, which one do you want?

**Comment by xiquinho** [comment]
do you know any snippet for bootstrap to expand/collapse the filters?

**Comment by xiquinho** [comment]
pl check search bar on tab A, is it OK now? What about the filters? I need your confirmation before re-write the other tabs. Ty & have a nice day!

**Comment by bo-io-gov-mo** [comment]
yes, tab A filter is ok. But the position and style not.

**Comment by xiquinho** [comment]
pl. check elements and layout tab A. After I understand what you really want I will fix position and styles.

**Comment by xiquinho** [comment]
pl. check if text/title, sort and pagination are working as desired.

**Comment by bo-io-gov-mo** [comment]
I'm make the **layout & design only** for present idea to you implement, because those hard to speak or mention, take a look here:
http://192.168.3.63/cn/search/?sc=0&tab=a&q=macau&n=&ya=

notice that's not final, it will change always.

**Comment by bo-io-gov-mo** [comment]
above project here: http://192.168.3.22:8080/tfs/DefaultCollection/_git/IO2016?_a=history

**Comment by xiquinho** [comment]
I can't open it

**Comment by bo-io-gov-mo** [comment]
login with your eimprensa account(fnunes)

**Comment by xiquinho** [comment]
bow is ok but yesterday was not.
