### ISSUE TITLE
Search page left filter

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#29]
At All tab: http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E6%B0%91%E6%94%BF%E7%B8%BD%E7%BD%B2

left 3 filter chinese text is:
1.法例
2.政府機關批示摘錄,通告及公告
3.公證署公告及其他公告
 
![image](https://cloud.githubusercontent.com/assets/19220046/17471753/fd69599a-5d78-11e6-8529-f4d295a39e23.png)

And after click a filter, it should be link back to first tab, not others tab.

**Comment by xiquinho** [comment]
"And after click a filter, it should be link back to first tab, not others tab."

Why not? I don't see what problem is/have display the results on each tab as each filter will always give results belonging to the correspondent tab. For example, filter A only give tab A results, filter B only give tab B results and filter C only give tab C results. They never give mixed results.

**Comment by xiquinho** [comment]
"left 3 filter chinese text is:"

Do you want the filters to display the same name as the tabs? pl. confirm, I am not sure if I got it right.

**Comment by bo-io-gov-mo** [comment]
answer question 1: Firstly the user search the data scope is tab all.  When the result came back, we need to provide same scope and all filter to user choice again, not limit it. This is case we assume that user not know A/B/C clearly. If user choice A or B or C tab firstly, you show the result of each one is correct.

question 2 : right, It should only change at first tab for more suitable.

**Comment by xiquinho** [comment]
“Firstly the user search the data scope is tab all.”

OK, but search the data scope and filter the data are two different things.

“When the result came back, we need to provide same scope”

We already do.

“and all filter to user choice again”

We also do. The filters only disappear after the user choose to filter the data.

“not limit it”

“We” don’t limit nothing. The limitation came from the user choice: If the user chooses to filter the results on filter A, filter B and Filter C don’t apply anymore. You cannot mix the filters on tab all, therefore once the user chooses one filter why display the other two? Any further filtration always gives null results.

“we assume that user not know A/B/C clearly”

If the user “not know A/B/C clearly” why did the user click it? We can only assume what the user clicks or do not what you imagine the user may know or may not know clearly…

“right, It should only change at first tab for more suitable.”

Excuse me, only change at first tab? The same filter with one name in a tab and another name in another tab is more suitable? More suitable for what? But, Ok…never mind, you are right, as you always are.

**Comment by nelson6699520** [comment]
As I known existing search funtion the most problem is user always don't know A / B / C clearly, we need to provide all scope of data for search. If we assume everyone know that is wrong, always complain by user since many years ago. We must change it, thus we solve this problem is provide all data tab for search. User Click the filter is limit the result, not limit the filter like you made. How user change the filter to A when he clicked Filter of B?

Others, for those user know document type and number exactly, we provide category FILTER pages for show. This is why I separate two things. Not mix them together. Mix together always cause complex and confuse to all user.

**Comment by xiquinho** [comment]
"Mix together always cause complex and confuse to all user. "

Agree. But that is exactly what YOU are doing: YOU mix all the results together and after that YOU give filters for the user separate something the " user always don't know ... clearly"... that's the problem.

"How user change the filter to A when he clicked Filter of B?"

Pl. came to my computer I will explain. O perhaps I am not understanding well what you want.

**Comment by xiquinho** [comment]
is still buggy but I need you to confirm if this is what you want before fix it.

http://betan.io.gov.mo/pt/search/?sc=0&tab=&q=fernando

**Comment by bo-io-gov-mo** [comment]
Great! That model is exactly what I want. go ahead to optimize it. many thanks!
