### ISSUE TITLE
 Legislação “法例”項目的內容

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#3]
“法例”項目的內容由四個標籤組成(4 tags)：
1) 法例；2) 國際法；3) 特區成立前法例；4) 其他。
1)Legislação 2)Direito Internacional 3)Legislação anterior à RAEM 4)Outros

![image](https://cloud.githubusercontent.com/assets/19220046/15067445/031ddc14-13a3-11e6-9710-3d17ed227ee0.png)

*Detail: [leis.docx](https://github.com/bo-io-gov-mo/website/files/251755/leis.docx)

**Comment by xiquinho** [comment]
4 tags??? do you mean 4 tabs?

**Comment by bo-io-gov-mo** [comment]
Yes. 4 tabs. and its content inside above word file.

**Comment by xiquinho** [comment]
How are you going to separate “LEI” (法律) before and after RAEM? There is no before/after filter, this is a common type.

**Comment by xiquinho** [comment]
Other examples: 法規	Regulamento, 議定書	Protocolo ,更正	Rectificação, 其他 Outro, these are common types in used before and after RAEm

**Comment by bo-io-gov-mo** [comment]
First tab "Legislação" include before and after RAEM, it is include few before REAM Legislação.
3nd tab "Legislação anterior à RAEM" their all content is before RAEM.

1st Tab: Legislação 法例

            中文            |                             葡文                            
----------------------------|-------------------------------------------------------------
 全國性法律及其他規範性文件 | Leis Nacionais / Doc. Regulamentares                        
 法律                       | Lei                                                         
 行政法規                   | Regulamento Administrativo                                  
 行政命令                   | Ordem Executiva                                             
 行政長官批示               | Despacho do Chefe do Executivo                              
 行政長官公告               | Aviso do Chefe do Executivo                                 
 行政法務司司長批示         | Despacho da Secretária para a Administração e Justiça       
 經濟財政司司長批示         | Despacho do Secretário para a Economia e Finanças           
 保安司司長批示             | Despacho do Secretário para a Segurança                     
 社會文化司司長批示         | Despacho do Secretário para os Assuntos Sociais e Cultura   
 運輸工務司司長批示         | Despacho do Secretário para os Transportes e Obras Públicas 
 廉政專員批示               | Despacho do Comissário contra a Corrupção                   
 審計長批示                 | Despacho do Comissário da Auditoria                         
 終審法院院長批示           | Despacho do Presidente do Tribunal de Última Instância      
 檢察長批示                 | Despacho do Procurador                                      
 立法會決議                 | Resolução (AL)                                              
 法規                       | Regulamento                                                 
 議定書                     | Protocolo                                                   
 更正                       | Rectificação                                                
 其他                       | Outro  



2rd tab: 國際法 Direito Internacional

 中文         |                    葡文                    
----------------------|--------------------------------------------
 國際公約             | Tratados Multilaterais                     
 聯合國安全理事會決議 | Resoluções do Conselho de Segurança da ONU 
 行政長官公告         | Avisos do Chefe do Executivo               
 雙邊協議             | Tratados Bilaterais                        
 區域協定             | Acordos Inter-Regionais                    
 國家                 | Lista Por País                             
 城市                 | Lista Por Cidade     
           

3rd tab: 特區成立前法例 Legislação anterior à RAEM

        中文               |                           葡文                          
-----------------------------------|---------------------------------------------------------
 立法性法規                        | Diploma Legislativo                                     
 法令                              | Decreto-Lei                                             
 省令                              | Decreto Provincial                                      
 訓令                              | Portaria                                                
 總督辦公室/澳門政府辦公室批示(GM) | Despacho GM                                             
 行政政務司批示                    | (SAA)	Despacho SAA                                      
 行政教育政務司批示                | (SAAE)	Despacho SAAE                                    
 行政、教育暨青年事務政務司批示    | (SAAEJ)	Despacho SAAEJ                                  
 行政法務司批示                    | (SAAJ)	Despacho SAAJ                                    
 衛生事務政務司批示                | (SAAS)	Despacho SAAS                                    
 社會事務暨預算政務司批示          | (SAASO)	Despacho SAASO                                  
 過渡期事務批示                    | (SAAT)	Despacho SAAT                                    
 經濟協調政務司批示                | (SACE)	Despacho SACE                                    
 傳播、旅遊暨文化事務政務司批示    | (SACTC)	Despacho SACTC                                  
 教育及中央行政政務司批示          | (SAEAC)	Despacho SAEAC                                  
 教育及公共行政政務司批示          | (SAEAP)	Despacho SAEAP                                  
 經濟文化事務司批示                | (SAEC)	Despacho SAEC                                    
 經濟財政事務政務司批示            | (SAEF)	Despacho SAEF                                    
 經濟財政運輸政務司批示            | (SAEFT)	Despacho SAEFT                                  
 社會設備政務司批示                | (SAES)	Despacho SAES                                    
 教育、衛生及社會事務政務司批示    | (SAESAS)	Despacho SAESAS                                
 大型建設政務司批示                | (SAGE)	Despacho SAGE                                    
 司法政務司批示                    | (SAJ)	Despacho SAJ                                      
 司法及行政自治政務司批示          | (SAJAA)	Despacho SAJAA                                  
 工務及房屋政務司批示              | (SAOPH)	Despacho SAOPH                                  
 保安事務政務司批示                | (SAS)	Despacho SAS                                      
 社會事務衛生司批示                | (SASAS)	Despacho SASAS                                  
 運輸工務司批示                    | (SATOP)	Despacho SATOP                                  
 批示                              | (其他)	Despacho (Outros)                                
 法律                              | (葡萄牙)	Lei (Portugal)                                 
 共和國總統命令                    | (葡萄牙)	Decreto do Presidente da República (Portugal)  
 共和國總統批示                    | (葡萄牙)	Despacho do Presidente da República (Portugal) 
 命令                              | (葡萄牙)	Decreto (Portugal)                             
 法令                              | (葡萄牙)	Decreto-Lei (Portugal)                         
 聯合批示                          | (葡萄牙)	Despacho Conjunto (Portugal)                   
 訓令                              | (葡萄牙)	Portaria (Portugal)                            
 決議                              | (葡萄牙)	Resolução (Portugal)                           


4th tab: 其他 Outros

 中文         |         葡文                    
-----------|--------------------
法典 | Códigos

**Comment by xiquinho** [comment]
ok, done.
