### ISSUE TITLE
text amend

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#30]
http://betan.io.gov.mo/cn/online
![image](https://cloud.githubusercontent.com/assets/19220046/17509157/1cb8cbaa-5e4b-11e6-9f57-dc35ad7a7799.png)
表格下載

**Comment by bo-io-gov-mo** [comment]
http://betan.io.gov.mo/cn/news
![image](https://cloud.githubusercontent.com/assets/19220046/17509188/47a8007e-5e4b-11e6-99d0-8cfba61439a0.png)
 2017年公眾假日

**Comment by bo-io-gov-mo** [comment]
http://betan.io.gov.mo/cn/home/suggestions
![image](https://cloud.githubusercontent.com/assets/19220046/17509230/8474a624-5e4b-11e6-8022-f2c4b7e18d52.png)
發送

**Comment by bo-io-gov-mo** [comment]
http://betan.io.gov.mo/cn/links
![image](https://cloud.githubusercontent.com/assets/19220046/17509257/a3ab0cb8-5e4b-11e6-8d77-3af65dadb7ff.png)

1. The link broken, pls change to this one: 
政府部門專題網站
Páginas Especializadas dos Serviços Governamentais
http://portal.gov.mo/web/guest/citizen/catpage?catid=858

2. pls add the following tile and put it at the first:
各政府部門網站
http://portal.gov.mo/web/guest/govwebsite

**Comment by xiquinho** [comment]
done, pl. check.
