### ISSUE TITLE
Missing pagination to show record

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#32]
Missing pagination to show record.
http://betan.io.gov.mo/cn/legis/list/a/46/?n=&ya=2014

![image](https://cloud.githubusercontent.com/assets/19220046/17579047/2b23a9d4-5fc3-11e6-9a28-2096b4cc24a0.png)

it also happen on:
http://betan.io.gov.mo/cn/legis/list/a/46/?n=&ya=2006
http://betan.io.gov.mo/cn/legis/list/a/46/?n=&ya=2002
http://betan.io.gov.mo/cn/legis/list/a/46/?n=&ya=1998

**Comment by xiquinho** [comment]
done, it was not the pagination and I fix a few more bugs, pl check all again.

**Comment by xiquinho** [comment]
done, it was not the pagination and I fix a few more bugs, pl check all again.
