### ISSUE TITLE
text of search bar

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#34]
The text change of chinese not correct:
1. 全文 (now is correct)
2. 標題 
3. 搜尋

![image](https://cloud.githubusercontent.com/assets/19220046/17582432/38741e1e-5fde-11e6-9192-8cf584c8d1e7.png)

**Comment by xiquinho** [comment]
done

**Comment by xiquinho** [comment]
not yet?
