### ISSUE TITLE
search performace

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#35]
http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E9%81%8A%E8%89%87
![image](https://cloud.githubusercontent.com/assets/19220046/17581734/28139896-5fda-11e6-9566-70c684b9b394.png)

http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E6%BE%B3%E9%96%80
![image](https://cloud.githubusercontent.com/assets/19220046/17581711/f5150c86-5fd9-11e6-819b-9defaed9a3f2.png)

**Comment by bo-io-gov-mo** [comment]
#28 

pls send me those sql count query.

**Comment by xiquinho** [comment]
done

**Comment by bo-io-gov-mo** [comment]
http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E6%BE%B3%E9%96%80
your timer show different of sql server management studio:
**Total Recs took 12 seconds**
Query took 3 seconds.
Filters took (I don't have filter query sql)

You are right, bottleneck seem at Total Recs query. Fortunately, I found a simply solution optimize total recs: 
````
Select TotalRecs FROM (SELECT COUNT(*) AS TotalRecs FROM vwIndexQuery As FT_TBL INNER JOIN ( SELECT SUM(t.Title_Rank) As Title_RANK, SUM(t.text_Rank) As Text_RANK, s.tboID,s.LinkID,s.tab FROM (Select [KEY], Rank As Title_Rank, 0 As Text_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033) UNION ALL SELECT [KEY], 0 As Title_Rank, Rank As Text_rank FROM CONTAINSTABLE(search, text_cn, N'澳門',language 1033) ) as t INNER JOIN Search AS s on t.[key]=s.tboID GROUP BY s.tboID, s.LinkID, s.tab ) As TBL_Rank On (FT_TBL.LinkID=TBL_Rank.LinkID And FT_TBL.cat=TBL_Rank.tab) ) As TBL_Display
````
try replace the **COUNT(*)** to **COUNT(ft_tbl.DiplomNamept+ft_tbl.DiplomDescpt)** , it is took about 2~3 seconds after.


These query need to transact with sql server at least 3 times. If possible, change it to store procedure it only transact one time, took 3~5 seconds at all.
```` 
execute GetFilteredTable   N'澳門', '', 24, 1
````

**Comment by xiquinho** [comment]
Filters took (I don't have filter query sql)

done

try replace the COUNT(*) to COUNT(ft_tbl.DiplomNamept+ft_tbl.DiplomDescpt) 

done

These query need to transact with sql server at least 3 times

I know, but that's not the problem here. Here talking about the time to transact only Total Recs not the time to transact the 3 queries. And the time to calculate Total Recs alone is the same by SP or script. I already test with SP (later send you a demo) and it seems the time is worse than now.

The problem in my opinion is the bad performance resulting from querying the view and the poor construction of the SQL string (Cases, If then, functions, etc in a SQL string always slow down the transaction).

**Comment by bo-io-gov-mo** [comment]
Yes, it slow at join the view with key table.
In my stored procedure, thinking about select query keyword into ram table first, second and others query from ram that table. The purpose hope join the view consume one time. But it may be not the best solution, and thank you for your try.

**Comment by bo-io-gov-mo** [comment]
now click the filter on first tab show nothing!
http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E5%9F%BA%E6%9C%AC%E6%B3%95&da=20

**Comment by xiquinho** [comment]
I mess up with something, tomorrow I will check

**Comment by bo-io-gov-mo** [comment]
After I saw your filter query in first tab. There needn't query filter many times, you can combine 3 filters into 1 query and add TAB to retrieve info. Then just separate to display on server manipulate and save database connection and query resource, it can optimize the performance.

**Comment by xiquinho** [comment]
This query:

Select TotalRecs FROM (SELECT COUNT(*) AS TotalRecs FROM vwIndexQuery 

Only works without filters. I need to find another solution to count the records when the user select the filters.

Can you send me again the code for the solution with the SP

**Comment by xiquinho** [comment]
you can combine 3 filters into 1 query and add TAB to retrieve info

I know I can, but I am trying to reuse the code and avoid querying the view. In my opinion, it is faster query 3 time the old tables than query the view 1 time, but that's not the problem now.

Before elaborate more can you add a counter to the solution with the SP to compare the results?

The code is something like this>

        Dim Durationtotalrecs As TimeSpan
        Dim StartTimetotalrecs As DateTime = DateTime.Now

(send the query to database here)

        Durationtotalrecs = DateTime.Now.Subtract(StartTimetotalrecs)
        totalTimetotalrecs = String.Format("Calculate Total Recs took {0} Milliseconds", Durationtotalrecs.Milliseconds.ToString())

**Comment by bo-io-gov-mo** [comment]
SP call: [GetFilteredTable] [query](http://192.168.3.22:8080/tfs/DefaultCollection/_git/betas/commit/8fd9036c5adb342714e63ca71b71698b31263e65?path=%2Fbetas%2FstoreProcedure.sql&gridItemType=2&_a=contents)
Server code at [LibIO.vb](http://192.168.3.22:8080/tfs/DefaultCollection/_git/betas/commit/8fd9036c5adb342714e63ca71b71698b31263e65) function call: GetDataTables

it reference from:
http://stackoverflow.com/questions/7239450/returning-multiple-tables-from-a-stored-procedure

**Comment by bo-io-gov-mo** [comment]
Remind you that above code only for demo show purpose, it is buggy and not enough for production.

**Comment by xiquinho** [comment]
For now, I am not planning to use it, I just want to compare the time to return the table one by one and the total records using the two methods.

**Comment by bo-io-gov-mo** [comment]
In my rough test at least 3~4x faster.

http://search2015.io.gov.mo/Search/?q=%E6%BE%B3%E9%96%80&s=r&t=c&i=s
page load: 4 seconds.

http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E6%BE%B3%E9%96%80
page load: 16 seconds.

**Comment by xiquinho** [comment]
You can’t compare like this. Only when the web and sql servers are in the same network, same memory, same cpu, etc, is acceptable to compare. I don’t know about search2015 but betan and the sql server are NOT in the same network, hence more slower.

**Comment by bo-io-gov-mo** [comment]
Yes, they are same network, same memory, same cpu.....same web server and same db server, only different is NOT same application.

**Comment by xiquinho** [comment]
betan and 192.168.12.20 are in the same network? I don't think so...

**Comment by bo-io-gov-mo** [comment]
I say above two link are same. **search2015** and **betan** are same web server, both connect to control\bo2004_search db. so they are SAME web server, db server, network connection.

**Comment by xiquinho** [comment]
Ok, I got it now. If you want to switch to SP on the first tab is OK, just let me know what you prefer. But it will take time, I need to rewrite everything for the first tab, including new because the filters from other tabs cannot be reused with the view.

**Comment by bo-io-gov-mo** [comment]
In my knowledge I only can suggest this way to optimize performance. Yes, I prefer store procedure .

**Comment by bo-io-gov-mo** [comment]
Have any update or issue about change the search to use SP?

**Comment by xiquinho** [comment]
Almost the entire page need to be re-written, I’m still working on it.

**Comment by xiquinho** [comment]
I had to rewrite part of the SP but have I’m not sure how to localize it. Let me know if you can help and if you can pl. came here I will explain. Also I need your help to test it.

**Comment by bo-io-gov-mo** [comment]
for sort order, pls take a look here:
 http://sqlperformance.com/2012/08/t-sql-queries/conditional-order-by

**Comment by bo-io-gov-mo** [comment]
I rewrited the SP call: GetFilteredTable_all_cn, it only work for first tab.

execute GetFilteredTable_all_cn @keywords, @typeId, @sortby, @pageSize, @page
@sortby=0 by rank
@sortby=1 by date DESC
@sortby=2 by date ASC

````
execute GetFilteredTable_all_cn  N'基本法', 0, 0, 24, 1
````

**Comment by xiquinho** [comment]
If you don’t include the tab parameter you will get filtered results from different tabs, for example when typeid = 28 Is this what you want? I think not…

**Comment by bo-io-gov-mo** [comment]
yes. I will add it.

**Comment by xiquinho** [comment]
Also, both tables need to return CATNAMECN as CATNAME and the filter table must return typeid value (I need it for the hyperlink)

**Comment by bo-io-gov-mo** [comment]
yes.

**Comment by bo-io-gov-mo** [comment]
done.
execute GetFilteredTable_all_cn @keywords, @typeId, @tab, @sortby, @pageSize, @page
````
execute GetFilteredTable_all_cn  N'基本法', 46, 'A', 0, 24, 1
````
if  _cn ok, I duplicate a _pt SP?

**Comment by xiquinho** [comment]
Yes, can you please change the tab value to lowercase? (to keep it consistent in all tabs)

**Comment by xiquinho** [comment]
Also, if you want to display the sql string you need to return it from the SP

**Comment by xiquinho** [comment]
Also, to display the filter tables only with the first 10 records with the ‘more’ link I need 3 different tables, one for each tab. Otherwise, the results are all mixed.

**Comment by bo-io-gov-mo** [comment]
done.

**Comment by xiquinho** [comment]
can I make changes on the SP?

**Comment by bo-io-gov-mo** [comment]
yes.

**Comment by xiquinho** [comment]
I just need all tables to return CATNAMECN as CATNAME

**Comment by xiquinho** [comment]
done, pl refresh if you have the sql page open

**Comment by bo-io-gov-mo** [comment]
can I duplicate a _pt version now or later?

**Comment by xiquinho** [comment]
I already duplicate, but I found something missing, how is this going to handle the text/only title option? ( More If, else, then? You're creating a monster...)

**Comment by bo-io-gov-mo** [comment]
it only need to switch #ALLREC query. yes. write SP very annoying with their rule , but it can process big data instantly.

**Comment by bo-io-gov-mo** [comment]
btw, sql server is not a search engine, we use it constrainedly. If you have time later, I suggest you research Solr or Google SEO.

**Comment by bo-io-gov-mo** [comment]
I will make one more parameter for title only / full text?

**Comment by xiquinho** [comment]
I never had intention to build a search engine with sql server, only search a database.

**Comment by xiquinho** [comment]
Yes for parameter for title only / full text, call it sc, pl.

**Comment by bo-io-gov-mo** [comment]
#ALLREC is base table of all. Hard to modify it. I'm trying....

**Comment by bo-io-gov-mo** [comment]
done.

add @sc= at first parameter. 0:fulltext, 1:title only.
````
execute GetFilteredTable_all_cn  0, N'基本法', 0, '', 0, 24, 1
````

**Comment by xiquinho** [comment]
I'm trying to combine CN and PT in the same SP, don't make changes until I finish.

**Comment by bo-io-gov-mo** [comment]
ok.

**Comment by xiquinho** [comment]
done, the modified version is:

GetFilteredTable_all_cn_pt

add parameter lang for culture and 
add DipOrder after DatePublished to correctly sort the results by date.

Pl. take a look, it is working but  not sure if can optimize something.

**Comment by bo-io-gov-mo** [comment]
performance drop so many, i don't know what cause, still looking:
 
````
execute GetFilteredTable_all_cn  0, N'澳門', 0, '', 0, 24, 1
````
4seconds



````
execute GetFilteredTable_all_cn_pt  0, N'澳門', 0, '', 0, 24, 1,'cn'
````
10seconds

**Comment by bo-io-gov-mo** [comment]
I think separate cn and pt are better, combine not good for performance and code review of maintain. pls.

**Comment by xiquinho** [comment]
Ok, if you prefer to maintain two SP, no problem. When finish optimize the CN version, pl send another for PT, I'm still finishing the new page.

**Comment by bo-io-gov-mo** [comment]
ok, I will make a pt version. thanks.

**Comment by bo-io-gov-mo** [comment]
I want to confirm what field must appear for you display and usage, now is:

SELECT 
						tbl_rank.tboID,
						**FT_TBL.LinkID,** 
						**FT_TBL.CAT AS Tab,** 
						**FT_TBL.DiplomNamecn AS DipNamecn,** 
						**FT_TBL.DiplomDesccn AS DipDesccn,**
						_FT_TBL.DiplomNamept AS DipNamept, 
						FT_TBL.DiplomDescpt AS DipDescpt,_
						**FT_TBL.DiplomUrl,** 
						**FT_TBL.BONumber**,
						**FT_TBL.BOYear**,
						**FT_TBL.Serie**,
						**FT_TBL.suplemento**,
	**(CASE WHEN ...) AS [Rank],** 
						FT_TBL.diplomlvl,
						**0 AS text_Rank,**
						**FT_TBL.DatePublished**,
**CatNameCN As CatNameCN,**
						_CatNamePT As CatNamePT,_
						**typeID**,
						**DipOrder**	


can I remove 5 field which not bold? (pt field put into pt version)

**Comment by xiquinho** [comment]
It is very hard to confirm now, let me try first with CN version and after that duplicate for PT. 

the  fields not in bold only appear on my version (GetFilteredTable_all_cn_pt),
I didn't change yours (GetFilteredTable_all_cn), it should be like before:

SELECT 
				tbl_rank.tboID,
				FT_TBL.LinkID, 
				FT_TBL.CAT AS Tab, 
				FT_TBL.DiplomNamecn AS DipName, 
				FT_TBL.DiplomDesccn AS DipDesc,
				FT_TBL.DiplomUrl, 
				FT_TBL.BONumber,
				FT_TBL.BOYear,
				FT_TBL.Serie,
				FT_TBL.suplemento, 				
				(CASE WHEN...
				FT_TBL.diplomlvl,
				0 AS text_Rank,
				FT_TBL.DatePublished,
				CatNameCN As CatName,
				typeID,
DipOrder 
including DipOrder to sort correctly by date

**Comment by xiquinho** [comment]
For PT it should be:

SELECT 
 tbl_rank.tboID,
 FT_TBL.LinkID, 
 FT_TBL.CAT AS Tab, 
 FT_TBL.**DiplomNamept** AS DipName, 
 FT_TBL.**DiplomDescpt** AS DipDesc,
 FT_TBL.DiplomUrl, 
 FT_TBL.BONumber,
 FT_TBL.BOYear,
 FT_TBL.Serie,
 FT_TBL.suplemento,

 (CASE WHEN...
 FT_TBL.diplomlvl,
 0 AS text_Rank,
 FT_TBL.DatePublished,
 **CatNamePT** As CatName,
 typeID,
 DipOrder

**Comment by bo-io-gov-mo** [comment]
ok, follow this first, change later if need.

**Comment by xiquinho** [comment]
but I need a SP named GetFilteredTable_all_pt there, same as CN version for now.

**Comment by bo-io-gov-mo** [comment]
ok, give me 5 mintues

**Comment by bo-io-gov-mo** [comment]
done, pls try.

**Comment by xiquinho** [comment]
looks good, ty!

**Comment by xiquinho** [comment]
nope, on filter tables CATNAMEPT should return as CATNAME, idem for CN, CATNAMECN should return as CATNAME

**Comment by bo-io-gov-mo** [comment]
done.

**Comment by bo-io-gov-mo** [comment]
Regard to question we discuss just now , it is mssql fts limitation, no way to count rank by **field weight**,  I made a trick to first order by **title_rank** , and second by **text_rank**.

Inside SP, title_rank name as [rank] that make you confuse here, but I want to emphasize is: [rank]=title_rank+diplomlvl

**Comment by bo-io-gov-mo** [comment]
mssql missing many many many... things of search feature required by modern. As I know is everyone give up mssql fts search in chinese world and find other solution.

**Comment by bo-io-gov-mo** [comment]
title_only query: https://github.com/bo-io-gov-mo/website/issues/26#issuecomment-231964881

**Comment by xiquinho** [comment]
I have now 3 queries for text:

a)	The original query you post in te first issu
b)	The query in search 2015 before the SP in the comment above
c)	The final query in the SP

I’m confused which should I use. I am going to change with this below for title only, please confirm and send me one similar for text.

WITH result_set AS 
(SELECT ROW_NUMBER() OVER (ORDER BY title_Rank DESC, DatePublished DESC) AS [row_number], TBL_Display.LinkID, TBL_Display.Tab , TBL_Display.DipName, TBL_Display.DipDesc, TBL_Display.DatePublished, TBL_Display.DiplomUrl, TBL_Display.BONumber, TBL_Display.BOYear, TBL_Display.Serie, TBL_Display.suplemento,  TBL_Display.diplomlvl, TBL_Display.org_title_Rank, TBL_Display.title_Rank as rank FROM (SELECT FT_TBL.LinkID, FT_TBL.CAT AS Tab,FT_TBL.DiplomNamecn AS DipName,FT_TBL.DiplomDesccn AS DipDesc,FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.suplemento , Title_Rank as org_title_Rank,(tbl_rank.title_Rank+isNull(FT_TBL.diplomlvl,0)*100) AS title_Rank, FT_TBL.diplomlvl,FT_TBL.DatePublished
 FROM vwIndexQuery AS FT_TBL INNER JOIN 
(
 SELECT t.Title_Rank AS Title_RANK, s.tboID,s.LinkID,s.tab FROM (SELECT [KEY], Rank as Title_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033))as t inner join Search as s on t.[key]=s.tboID
)
AS TBL_Rank on (FT_TBL.LinkID=TBL_Rank.LinkID and FT_TBL.cat=TBL_Rank.tab)) AS TBL_Display
) SELECT * FROM result_set WHERE [row_number] BETWEEN 0 AND 24

**Comment by bo-io-gov-mo** [comment]
yes, above query is as same as SP. It is correct qeery for title only.

**Comment by xiquinho** [comment]
ty, can you send me the updated query for text also? pl. type here.

**Comment by bo-io-gov-mo** [comment]
did you talking about Tab A,B,C. Now in betan tab A,B,C query are fine both full text and title only, did you found something incorrect?

**Comment by xiquinho** [comment]
I don’t know, I just found the queries in betan, search2015 and the SP are all different. I don’t know which one you want I use for tab A,B,C. It is not incorrect but probably it will give different results if they are not all the same.

**Comment by xiquinho** [comment]
Betan and SP seems to give the same results but different output.

Search2015 give different results and different output, so I cannot copy the query from there. But before, on the comment above, you told me to do so. But I cannot, probably search2015 query for text is outdated.

you can try by yourself searching for 澳門 in the 3 places.

**Comment by xiquinho** [comment]
Another examples:

In betan sortby have conditions:

ORDER BY (Case When KEY_TBL.title_Rank > 0 Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, text_Rank DESC, DatePublished DESC, DipOrder DESC

While the SP sortby  is more straightforward and the conditions are in a different place and they are diferent:

ORDER BY [rank] DESC, text_Rank DESC, DatePublished DESC) as [row_number]

Are they similar?

The CASE condition is different also, in SP includes diplomlvl:

 (CASE WHEN title_Rank > 0 THEN tbl_rank.title_Rank+isNull(FT_TBL.diplomlvl,0)*100 ELSE tbl_rank.title_Rank END) AS [Rank], 

I’m fugging confused with all this…

**Comment by bo-io-gov-mo** [comment]
question1:  I found the first difference is  tab A query have a last condition:
````
.... AND FT_TBL.DipDisplay = 1
````
I already set into vwIndexQuery , the result records count same now.

question2: CASE condition is different: because both is different runnuing environment, SP is base on a #temp table. I can write query like SP (similar as search2015), but it will cause sql more complex and slower.

**Comment by xiquinho** [comment]
Question 1 I already explain this before, records approved to appear on the search must obey both conditions:

Active = True AND Dipdisplay = 1

The reason is, for example, sometimes we need to create dummy records when a BO is published without any content for part A but we don’t want these records appear in the search. Because they are dummy and it’s a hack.

Question 2 I will explain personally.

**Comment by bo-io-gov-mo** [comment]
The below query logic is same as SP, only different order by.

--TAB A fulltext query ---------------------

With result_set As (Select ROW_NUMBER() OVER ( ORDER BY (Case When KEY_TBL.title_Rank > 0 
Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, text_Rank DESC, DatePublished DESC, DipOrder DESC ) AS [row_number], FT_TBL.DiplomNamecn As DipName, FT_TBL.DiplomDesccn As DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab, KEY_TBL.Title_RANK as RANK FROM tbo2004 As FT_TBL 
INNER JOIN 
(

**SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_cn, N'澳門',language 1033) ) as t inner join Search as s on t.[key]=s.tboID GROUP BY s.tboID, s.LinkID, s.tab** 

) 
AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='A') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) 
Select * FROM result_set 


----------------------------

--TAB A title only query-------------------------------

With result_set As (Select ROW_NUMBER() OVER ( ORDER BY (Case When KEY_TBL.title_Rank > 0 
Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC,  DatePublished DESC, DipOrder DESC ) AS [row_number], FT_TBL.DiplomNamecn As DipName, FT_TBL.DiplomDesccn As DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab, KEY_TBL.Title_RANK as RANK 
FROM tbo2004 As FT_TBL
 INNER JOIN 
(

**SELECT t.Title_Rank AS Title_RANK, s.tboID,s.LinkID,s.tab FROM (SELECT [KEY], Rank as Title_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033))as t inner join Search as s on t.[key]=s.tboID**

) 
AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='A') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) 
Select * FROM result_set

**Comment by xiquinho** [comment]
Ty! Is it possible to transform the ORDER BY clause into something just like the SP. I mean instead of:

ORDER BY (Case When KEY_TBL.title_Rank > 0 
Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, text_Rank DESC, DatePublished DESC, DipOrder DESC

Could it be:

ORDER BY Rank DESC, text_Rank DESC, DatePublished DESC, DipOrder DESC

Passing the expression inside the case as an alias as [rank]? It would simplify a lot my code and the logic behind it.

**Comment by bo-io-gov-mo** [comment]
Yes, use a SELECT include original select table, like:

With result_set As (Select ROW_NUMBER() OVER ( ORDER BY [**Rank**] DESC, text_Rank DESC, DatePublished DESC, DipOrder DESC ) AS [row_number], TBL_Display.LinkID, TBL_Display.Tab , TBL_Display.DipName, TBL_Display.DipDesc, TBL_Display.DatePublished, TBL_Display.DiplomUrl, TBL_Display.BONumber, TBL_Display.BOYear, TBL_Display.Serie, TBL_Display.suplemento, TBL_Display.[Rank] as [rank],TBL_Display.text_Rank,TBL_Display.DipOrder 
FROM 
(
**SELECT FT_TBL.DiplomNamecn As DipName, FT_TBL.DiplomDesccn As DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento,  'a' as Tab,  (CASE WHEN title_Rank > 0 THEN KEY_TBL.title_Rank+isNull(FT_TBL.Visits_cn,0)*100 ELSE KEY_TBL.title_Rank END) AS [Rank],
KEY_TBL.Text_RANK,FT_TBL.DipOrder FROM tbo2004 As FT_TBL** 
INNER JOIN 
(
**SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_cn, N'澳門',language 1033) ) as t inner join Search as s on t.[key]=s.tboID GROUP BY s.tboID, s.LinkID, s.tab**
) 
AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='A') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) AS TBL_Display
) 
Select * FROM result_set

 ------------------------

 
 With result_set As (Select ROW_NUMBER() OVER ( ORDER BY [**Rank**] DESC, DatePublished DESC, DipOrder DESC ) AS [row_number], TBL_Display.LinkID, TBL_Display.Tab , TBL_Display.DipName, TBL_Display.DipDesc, TBL_Display.DatePublished, TBL_Display.DiplomUrl, TBL_Display.BONumber, TBL_Display.BOYear, TBL_Display.Serie, TBL_Display.suplemento, TBL_Display.[Rank] as [rank],TBL_Display.DipOrder 
FROM 
(
**SELECT FT_TBL.DiplomNamecn As DipName, FT_TBL.DiplomDesccn As DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab, (CASE WHEN title_Rank > 0 THEN KEY_TBL.title_Rank+isNull(FT_TBL.Visits_cn,0)*100 ELSE KEY_TBL.title_Rank END) AS [Rank],
FT_TBL.DipOrder FROM tbo2004 As FT_TBL** 
INNER JOIN 
(
**SELECT t.Title_Rank AS Title_RANK, s.tboID,s.LinkID,s.tab FROM (SELECT [KEY], Rank as Title_Rank FROM CONTAINSTABLE(search, title_cn, N'澳門',language 1033))as t inner join Search as s on t.[key]=s.tboID**
) 
AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='A') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) AS TBL_Display
) 
Select * FROM result_set

**Comment by xiquinho** [comment]
On the SP, filtered tables can you change the name of column:
Count 
to:
TotalRecs

TY!

**Comment by bo-io-gov-mo** [comment]
done.

**Comment by xiquinho** [comment]
I upload a new version, can you help to test only first tab, filters, sort and pagination? The other tabs and put all together I will finish soon.

**Comment by bo-io-gov-mo** [comment]
sure.

**Comment by xiquinho** [comment]
Just to let you know, I’m renaming the filter sc to o (only title) IF you want to change it on the SP. Sorry for the inconvenience.

**Comment by bo-io-gov-mo** [comment]
Renamed sc in SP cause web pages show error, I haven't changed it.

**Comment by bo-io-gov-mo** [comment]
Now search http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=%E6%BE%B3%E9%96%80 took 6~9 seconds, can optimize it more better?

**Comment by xiquinho** [comment]
it's slow but not that slow, can you show me?

**Comment by bo-io-gov-mo** [comment]
I can accept it, because it this search case is very special. I just want to know still have any space to optimize?

**Comment by xiquinho** [comment]
yes, but I don't have time yet. And not much space but a little perhaps.

**Comment by xiquinho** [comment]
beside, right now beta12 have 256Mb free memory, what do you expect? buy more memory, perhaps? do you need money?

**Comment by bo-io-gov-mo** [comment]
I share with you if I have.

**Comment by xiquinho** [comment]
what database you will use in production? bo2004 or 2004_search?

**Comment by bo-io-gov-mo** [comment]
In my mind bo2004_search only for development provisional, bo2004 is the main db for replication of publication. Any idea easy to make bo2004 as same as bo2004_search? or others solution?

**Comment by xiquinho** [comment]
right now, my concern is the connection strings, in some places we are using BO2004 and another BO2004s, we need to point all to the same DB. Hence , we need to choose one.

**Comment by bo-io-gov-mo** [comment]
right now we choose **bo2004_search** is better, but it is subscribe data from **bo2004**. We will stop bo2004 finally (needn't maintain two different db), you not concern about this? I means replication to others.

**Comment by xiquinho** [comment]
On beta you need to keep using **BO2004**. Just copy the view and the SP’s from **bo2004_search** to **bo2004** and I will add it to the replication. My concern is something fail but if fail I will need to fix it, that’s all.

**Comment by xiquinho** [comment]
btw, how did you create bo2004_search ?

**Comment by bo-io-gov-mo** [comment]
I remember following done on bo2004_search:
1. create two views (2).
2. create table search(1).
3. create full text search catalog(1) and clear stopwords(1).
4. create store procedure(2).
5. create index on query tables name:_fts(5).

We need to implement above to bo2004. I think it is ok.

**Comment by xiquinho** [comment]
no, I mean how do you create the database the first time?

**Comment by bo-io-gov-mo** [comment]
not me, it created by yourself

**Comment by xiquinho** [comment]
Did I? I forgot completely… but the important thing is we cannot replace **BO2004** with **bo2004_search**, the only way to do it is to restore from a backup which I didn’t. So you need to redo the above steps on **Bo2004**. I suggest only make changes when you are sure everything is final to avoid any disruptions.

**Comment by bo-io-gov-mo** [comment]
agree.

**Comment by bo-io-gov-mo** [comment]
start another new issue to discuss db migrate. #66
