### ISSUE TITLE
adjust search page minor layout

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#36]
I want adjust many minor layout/margins/space/color things adjust on the search page, it may be adjust many times until finalize. I write down it to you modify, or I can adjust it by myself, please let me know how is convenience to you and cooperation together.

**Comment by xiquinho** [comment]
I suggest finish first all requirements, all tests and when is bug free adjust the minor layout/margins/space/color things.

If you want to adjust by yourself, you need to warn me first, I need to check-in the page, you will need to check-out and only after that make any changes. that's the only safe way to make changes on the same page at the same time.

**Comment by xiquinho** [comment]
can close or need any clarification more?
