### ISSUE TITLE
display no result text

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#37]
http://betan.io.gov.mo/cn/search/?sc=1&tab=&q=hello
pls display text when search no result match, such as:
![image](https://cloud.githubusercontent.com/assets/19220046/17614830/17534660-609c-11e6-9eb2-17babfaf56c8.png)

**Comment by xiquinho** [comment]
done if disappear again, don't worry it's due to testing

**Comment by xiquinho** [comment]
Also, the sort is not working correctly, I am aware of it but I can only fix it in the end. no need to open ticket.

**Comment by bo-io-gov-mo** [comment]
noted.
