### ISSUE TITLE
behavior of change tab 

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#38]
If user click change the tab, can re-search with the same keyword in those tab data scope. or just reset it? now click tab is only change the tab options, but the result may be not belong the tab.

**Comment by xiquinho** [comment]
If user click change the tab, can re-search with the same keyword in those tab data scope but the year change on each tab.

"but the result may be not belong the tab."

the result belongs to the tab the user search

**Comment by bo-io-gov-mo** [comment]
I means case example:
1. I click TAB A, type keyword [道路交通法](http://betan.io.gov.mo/cn/search/?sc=0&tab=a&q=%E9%81%93%E8%B7%AF%E4%BA%A4%E9%80%9A%E6%B3%95&n=&ya=)
2. I click  TAB B.

At this time, the result show is only appear on tab A, it will make confuse on the screen display. I suggest re-search it on TAB B is better.

**Comment by xiquinho** [comment]
to re-search you need to click on the button Search

**Comment by xiquinho** [comment]
can close or need any additional clarification?

**Comment by xiquinho** [comment]
pl clarify what you want I do with this, if not pl. close.

**Comment by bo-io-gov-mo** [comment]
if use click change tab, pls perform a re-search on that tab. example like: http://epub.cnki.net/kns/brief/default_result.aspx

**Comment by xiquinho** [comment]
The tabs were designed only for the user input their choices.

Now, if you want to also display the results without click on the search button, this will require a substantial amount of time to change because a lot of things need to be modified to accommodate it (pagination, sort, filters, etc).

I can do it but I will need more time to redesign and test it, is not simple to change.

**Comment by bo-io-gov-mo** [comment]
ok, I got it. postpone develop this feature now.

**Comment by xiquinho** [comment]
what I can do more easier is clear the previous results when the user change the tab. Do you want?

**Comment by bo-io-gov-mo** [comment]
yes. may be better.

**Comment by xiquinho** [comment]
Is OK now or not yet?

**Comment by bo-io-gov-mo** [comment]
ok
