### ISSUE TITLE
can't not display pdf second pages on mobile/ device.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#39]
Can't not display pdf second pages or under on mobile/tablet browser, either android or ios, I suggest change it to picture.

http://betan.io.gov.mo/cn/about/policy
http://betan.io.gov.mo/cn/home/pledge

**Comment by xiquinho** [comment]
Pl. send the picture I will replace.

**Comment by bo-io-gov-mo** [comment]
After I try switch it to picture, I realized it is not a good solution. like bad resolution, quality and need to transform it everytime later amend. I know the solution change a pdf viewer which support mobile and tablet  browser, such as pdf.js https://github.com/mozilla/pdf.js

**Comment by xiquinho** [comment]
Why do you have to display pdf in first place? 

Would not be simpler to display text like all the other pages?

**Comment by bo-io-gov-mo** [comment]
I know they want display it as original pdf format.

**Comment by xiquinho** [comment]
I don’t care about what they want, it is clear they don’t have any idea about what they are doing or how to do what they want. I just care about web design and these documents are designed for printing and evidently not suitable to display on web format. 

But, OK, never mind, nothing in this website is suitable for display, one or two more pages don’t make any difference.

**Comment by xiquinho** [comment]
And I can’t access 
http://betan.io.gov.mo/
on mobile devices

**Comment by bo-io-gov-mo** [comment]
use SSID: IO-INTERNET  
(use your email account login)

**Comment by xiquinho** [comment]
can't see any problem but i only have windows phone here, can you show me?

**Comment by bo-io-gov-mo** [comment]
I follow the pdf.js example and made a demo on: http://192.168.3.22/test2/embedpdf.html , it work both desktop and mobile.

**Comment by xiquinho** [comment]
can you zip and send me the files at

http://192.168.3.22/test2/embedpdf.html

Ty & have a nice day!

**Comment by bo-io-gov-mo** [comment]
I download it on https://mozilla.github.io/pdf.js , better is you take a look.

**Comment by xiquinho** [comment]
How do you pass the file name to the viewer?

**Comment by bo-io-gov-mo** [comment]
I only change DEFAULT_URL in viewer.js, it is not the best practice. And I found it can't cross site reference pdf due to some security reason.

**Comment by xiquinho** [comment]
This is a total nonsense in another level: more 365 files to website, a security problem, a nightmare to maintain, (it is just a question of time until this stop to work alone), hard to configure, and unknown number of devices it works or not  and solves nothing: only for display pages the user can’t read. Well done Mr. Nelson…

**Comment by bo-io-gov-mo** [comment]
pdf.js is one of well-know javascript based pdf viewer, it is built in firefox now. We only use it like a component if not change its default function. I say security problem is not viewer itself. pls take a look: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

Now, the problem is the embed pdf can't show on mobile device, my solution is use a compatible viewer to show it. that's all.

**Comment by bo-io-gov-mo** [comment]
I think other solution is: show embed pdf on wide screen like now,  show a thumb pic link to pdf when on mobile screen. Most mobile browser have built in pdf viewer, it only not support show embed display well. Then you needn't use another pdf viewer.

**Comment by xiquinho** [comment]
Pl. try http://betan.io.gov.mo/pt/home/pledge on your devices or lend me for I try myself

**Comment by bo-io-gov-mo** [comment]
Some device success and some fail. It is proof that pdf.js not enough compatible, give up. Can you try last solution of above.

**Comment by xiquinho** [comment]
But that is obvious, Nelson… Even if it works NOW in your Iphone and NOW in your Samsung, how do you know within one year or two years, with different browsers, different devices, different OS, thousands of combinations, how do you know it will work? Of course you don’t know and the only thing you know is the only solution safe is text mode. All other solutions are lame solutions. But you know all this and make me very tired repeat and explain the same things over and over and over…

**Comment by bo-io-gov-mo** [comment]
I know the most safe is text and picture of standard HTML, I know again! But require is show ORIGINAL PDF document. And we try to find a solution to show pdf in mobile. Do you think direct link not safe in mobile? Now, I know that embed is not good to show pdf in mobile or let me know other solution to show PDF in mobile.
![image](https://cloud.githubusercontent.com/assets/19220046/17693195/362cfa9a-63d0-11e6-945e-70587380b3a3.png)
http://images.io.gov.mo/cn/about/ISO9001_ISO14001.pdf

**Comment by bo-io-gov-mo** [comment]
if we can't find show pdf solution at last, I will try to switch it to pictures again, do you agree?

**Comment by xiquinho** [comment]
But require by who? Only someone without any idea about web design and what is doing can make a require like this. that's the problem. Do you already explain her this is totally wrong? Did you explain her this is incompatible with responsive design? Did you already explain her this is not suitable for read in a mobile phone? I have my doubts....

**Comment by bo-io-gov-mo** [comment]
I'm not agree display a pdf on website is totally wrong. I repeat again is required to show these original document on website.

**Comment by xiquinho** [comment]
“I'm not agree display a pdf on website is totally wrong”

I never said that. What I am saying is in THIS situation a pdf is not justifiable and THIS pdf is not suitable for THIS situation. 

The pdf pledge, for example, was designed for a poster, I remember to see it in the walls and now you want to display it in a mobile phone correctly? Give me a break, please….

“I will try to switch it to pictures again, do you agree”

If I agree or not is not important. What is important is don’t replace the bad with the worse. Let me thing about a possible solution for this and I will let you know.

**Comment by nelson6699520** [comment]
Ok, pls find a solution to display these pdf both on desktop and mobile.

**Comment by xiquinho** [comment]
The first think is find where is the problem and for that I need to test but I only have windows phone here and there everything looks fine.

**Comment by bo-io-gov-mo** [comment]
The problem is appear in Android and ios system browser.

**Comment by xiquinho** [comment]
ok, I will check after I finish boheader.

**Comment by bo-io-gov-mo** [comment]
This problem also appear on below cases:
http://betabo.io.gov.mo/bo/ii/2016/33/aviso56_cn.asp

**Comment by bo-io-gov-mo** [comment]
pls hold this issue. I noted these pdf will change with hyperlink later. I will update information to you later. thanks.

**Comment by bo-io-gov-mo** [comment]
pls make text links inside below pages and link to relate pdf file:

http://betan.io.gov.mo/cn/about/policy
品質及環境管理體系政策 ([iso_política_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426177/iso_politica_cn.pdf))
品質及環境管理體系目標 ([iso_objectivo_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426178/iso_objectivo_cn.pdf))

http://betan.io.gov.mo/pt/about/policy
Política do Sistema de Gestão Qualidade e Ambiental (pdf same as cn)
Objectivo do Sistema de Gestão de Qualidade e Ambiental (pdf same as cn)

=========

http://betan.io.gov.mo/cn/home/pledge
抱負、使命及信念 ([1_vision_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426205/1_vision_cn.pdf))
服務承諾的履行情況 ([2_execute_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426207/2_execute_cn.pdf))
滿意度調查概況 ([3_survey2015_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426208/3_survey2015_cn.pdf))
滿意度調查總結報告 ([4_Report2015_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426209/4_Report2015_cn.pdf))
建議、投訴及異議的概況 ([5_suggestion2015_cn.pdf](https://github.com/bo-io-gov-mo/website/files/426210/5_suggestion2015_cn.pdf))



http://betan.io.gov.mo/pt/home/pledge
Visão, Missão e Crença ([1_vision_pt.pdf](https://github.com/bo-io-gov-mo/website/files/426212/1_vision_pt.pdf))
Situação da execução da Carta de Qualidade ([2_execute_pt.pdf](https://github.com/bo-io-gov-mo/website/files/426213/2_execute_pt.pdf))
Situação do grau de satisfação do inquérito ([3_survey2015_pt.pdf](https://github.com/bo-io-gov-mo/website/files/426214/3_survey2015_pt.pdf))
Situação das sugestões, queixas e reclamações ([4_suggestion2015_pt.pdf](https://github.com/bo-io-gov-mo/website/files/426215/4_suggestion2015_pt.pdf))

**Comment by xiquinho** [comment]
PT only 4 files?

**Comment by bo-io-gov-mo** [comment]
yes.

**Comment by xiquinho** [comment]
done, pdf files will show tomorrow.
