### ISSUE TITLE
category of tile display order not consistency

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#40]
pls consistency display order of portuguese and chinese version, I suggest chinese follow portugese display sort order.

http://betan.io.gov.mo/pt/legis/int/multi
http://betan.io.gov.mo/cn/legis/int/multi

http://betan.io.gov.mo/pt/legis/int/bilat
http://betan.io.gov.mo/cn/legis/int/bilat

http://betan.io.gov.mo/pt/legis/int/region
http://betan.io.gov.mo/cn/legis/int/region

**Comment by xiquinho** [comment]
done, pl. check.

**Comment by bo-io-gov-mo** [comment]
the following have same issue:

http://betan.io.gov.mo/pt/entities/priv
http://betan.io.gov.mo/cn/entities/priv

http://betan.io.gov.mo/pt/entities/assoc
http://betan.io.gov.mo/cn/entities/assoc

**Comment by xiquinho** [comment]
All have. they were sorted according with the previous instructions.

**Comment by bo-io-gov-mo** [comment]
pls adjust above link of chinese follow portugese display sort order.

**Comment by xiquinho** [comment]
done.
