### ISSUE TITLE
hidden the title when no content.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#41]
pls hide the title that no content.
http://betan.io.gov.mo/cn/entities/admpub/rec/11220
![image](https://cloud.githubusercontent.com/assets/19220046/17616372/e12ea768-60a6-11e6-8f50-b2ecef482f3a.png)

**Comment by xiquinho** [comment]
they hide if no content, this is another error

**Comment by xiquinho** [comment]
done
