### ISSUE TITLE
missing content.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#42]
missing content.

http://betan.io.gov.mo/cn/entities/admpub/cat/30000
http://cn.io.gov.mo/Legis/record/30000.aspx

http://betan.io.gov.mo/cn/entities/admpub/cat/40000
http://cn.io.gov.mo/Legis/record/40000.aspx

**Comment by xiquinho** [comment]
done, pl check:
http://betan.io.gov.mo/cn/entities/admpub/rec/30000
http://betan.io.gov.mo/cn/entities/admpub/rec/40000
