### ISSUE TITLE
others link broken

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#44]
1. All links was show error. 
2. pls open a new windows to display them.

http://betan.io.gov.mo/cn/links/others

**Comment by xiquinho** [comment]
this is not an error, I didn't build the records page yet, it will take a while.

**Comment by xiquinho** [comment]
Is not clear if you want:

1 - Display in a record page like before (slower)
or 
2 - Only the link opening in a new page (faster)

would you mind to clarify, please?

**Comment by xiquinho** [comment]
don, pl. check.
