### ISSUE TITLE
no content display

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#45]
http://betan.io.gov.mo/cn/legis/list/a/48

**Comment by xiquinho** [comment]
done

**Comment by bo-io-gov-mo** [comment]
It always show as below, you are different?

![image](https://cloud.githubusercontent.com/assets/19220046/17618144/a56e0d4a-60b0-11e6-9911-3fa9b9042071.png)

**Comment by xiquinho** [comment]
sorry, upload wrong file, now ok
