### ISSUE TITLE
text overflow on portuguese

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#46]
http://betan.io.gov.mo/pt/legis
![image](https://cloud.githubusercontent.com/assets/19220046/17616924/b0d29b1c-60a9-11e6-9561-3259f3cd8e31.png)

**Comment by bo-io-gov-mo** [comment]
same issue:
http://betan.io.gov.mo/pt/legis/int/multi
![image](https://cloud.githubusercontent.com/assets/19220046/17617003/1f0116cc-60aa-11e6-8df6-9b9c81264cba.png)

**Comment by bo-io-gov-mo** [comment]
same issue:
http://betan.io.gov.mo/pt/entities/admpub/rec/12000
![image](https://cloud.githubusercontent.com/assets/19220046/17617070/77de5aca-60aa-11e6-82e3-1540e020002e.png)

**Comment by xiquinho** [comment]
done 

(maybe have more, I will try to catch all)
