### ISSUE TITLE
Add hierarchy of path

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#48]
Add hierarchy of path:
http://betan.io.gov.mo/pt/legis/list/a/33

![image](https://cloud.githubusercontent.com/assets/19220046/17654602/5628988a-62d7-11e6-9d57-40744e9bc778.png)

http://betan.io.gov.mo/cn/legis/list/a/33
![image](https://cloud.githubusercontent.com/assets/19220046/17654638/c089db4e-62d7-11e6-8c34-b4aba589d5b7.png)

**Comment by xiquinho** [comment]
and link to where?

**Comment by bo-io-gov-mo** [comment]
http://betan.io.gov.mo/pt/legis/   (Legislação anterior à RAEM tab.)

**Comment by xiquinho** [comment]
It's a repeat link, not a hierarchy...

**Comment by bo-io-gov-mo** [comment]
Yes, my mention not exactly. But they in different tab.

**Comment by xiquinho** [comment]
ok, no problema...

**Comment by xiquinho** [comment]
done, pl. check

**Comment by bo-io-gov-mo** [comment]
can stay it at tab of Legislação anterior à RAEM ?

**Comment by xiquinho** [comment]
can but in a diferente URL

**Comment by bo-io-gov-mo** [comment]
yes, try.

**Comment by xiquinho** [comment]
done, pl. check
