### ISSUE TITLE
Missing context information of Chefe do Executivo,  JUSTICE(s)...

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#5]
![image](https://cloud.githubusercontent.com/assets/19220046/15068186/0ef1fc50-13a8-11e6-87bf-ab9f2d5dce17.png)

![image](https://cloud.githubusercontent.com/assets/19220046/15068264/98293998-13a8-11e6-9ed0-a1e1b92d7a4d.png)

**Comment by xiquinho** [comment]
Can you include the URL's with the pictures, please? I am a little bit lost about the meaning of this...

**Comment by bo-io-gov-mo** [comment]
link contrast here:

http://betan.io.gov.mo/cn/entities/admpub/cat/10000
http://cn.io.gov.mo/Legis/record/10000.aspx

------
http://betan.io.gov.mo/cn/entities/admpub/cat/11000
http://cn.io.gov.mo/Legis/record/11000.aspx

---------
http://betan.io.gov.mo/cn/entities/admpub/cat/12000
http://cn.io.gov.mo/Legis/record/12000.aspx

------------
http://betan.io.gov.mo/cn/entities/admpub/cat/13000
http://cn.io.gov.mo/Legis/record/13000.aspx


------------
http://betan.io.gov.mo/cn/entities/admpub/cat/14000
http://cn.io.gov.mo/Legis/record/14000.aspx

------------
http://betan.io.gov.mo/cn/entities/admpub/cat/15000
http://cn.io.gov.mo/Legis/record/15000.aspx

**Comment by xiquinho** [comment]
you are confusing categories with records, the old page is a record:
http://cn.io.gov.mo/Legis/record/10000.aspx
and the new record is now here:
http://betan.io.gov.mo/cn/entities/admpub/rec/10000

Should be under legis but you told me to pu all under admpub, or not?

**Comment by bo-io-gov-mo** [comment]
We want the result as below:

![image](https://cloud.githubusercontent.com/assets/19220046/15139569/63d2de3c-16c9-11e6-8922-25804fa0dcff.png)

link1: http://betan.io.gov.mo/cn/entities/admpub/rec/10000 (show Entidades Públicas tab)
![image](https://cloud.githubusercontent.com/assets/19220046/15139650/cbfe5324-16c9-11e6-816f-26516e0324b7.png)

link2: http://betan.io.gov.mo/cn/entities/admpub/rec/11000 (show Entidades Públicas tab)

link3: http://betan.io.gov.mo/cn/entities/admpub/rec/12000 (show Entidades Públicas tab)

link4: http://betan.io.gov.mo/cn/entities/admpub/rec/13000 (show Entidades Públicas tab)
 
link5: http://betan.io.gov.mo/cn/entities/admpub/rec/14000 (show Entidades Públicas tab)
 
link6: http://betan.io.gov.mo/cn/entities/admpub/rec/15000 (show Entidades Públicas tab)

**Comment by xiquinho** [comment]
not sure if this is what you want but pl. take a look and let me know.

**Comment by bo-io-gov-mo** [comment]
Yes, like this. Please continuous complete its contents.

**Comment by xiquinho** [comment]
complete what contents? Is something missing?

**Comment by bo-io-gov-mo** [comment]
The contents issue as same as #7 , I close this and discuss on (#7) .
