### ISSUE TITLE
BO year display

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#51]
http://betan.io.gov.mo/cn/bo/
![image](https://cloud.githubusercontent.com/assets/19220046/17765281/708e3ae0-6557-11e6-8382-ded16051c869.png)

**Comment by xiquinho** [comment]
I am not sure what you want. delete the year?

**Comment by bo-io-gov-mo** [comment]
yes.
1. remove the year column.
2. delete the year text in bo name.
3. add a combobox to select and change the year instead year column link.

**Comment by xiquinho** [comment]
done, pl check.
