### ISSUE TITLE
Legislação and news display

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#52]
pls combine boNo and date column together, display like homepage flexisel text

http://betan.io.gov.mo/cn/legis/list/a/46 , http://betan.io.gov.mo/cn/news/list/b/11
![image](https://cloud.githubusercontent.com/assets/19220046/17765673/e636bde2-6559-11e6-9949-566542209bea.png)

![image](https://cloud.githubusercontent.com/assets/19220046/17765828/b8fc5c8c-655a-11e6-8666-a46c3501e79a.png)

**Comment by xiquinho** [comment]
done, pl check.
