### ISSUE TITLE
link by external

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#53]
I would to know if other external link to our cn/pt/en website, for example:
http://www.macaolaw.gov.mo/cn/index2.asp homepage 
````
....
<iframe src="http://cn.io.gov.mo/rss/bo/lastupdates.aspx?serie=1" width="100%" height="100%" frameborder="0"></iframe>
....
````

such as something like rss function which others website already link.

**Comment by xiquinho** [comment]
I know have others such as www.gov.mo but I don't know and I don't have a complete list.

**Comment by xiquinho** [comment]
btw, the rss function is to keep running on the old website, I am not planning to move it.

**Comment by xiquinho** [comment]
pl clarify what you want I do with this, if not pl. close.

**Comment by bo-io-gov-mo** [comment]
consider some mechanism to redirect page or avoid display error/no page?

**Comment by xiquinho** [comment]
I already said:

> the rss function is to keep running on the old website, I am not planning to move it.

rss cannot be moved without error, therefore there is no redirect or any error to display. What do you want to do?

**Comment by bo-io-gov-mo** [comment]
ok, above link is inside rss, I got it now.
