### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#54]
below search show error:
http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E5%BD%AD%E6%B7%91%E5%AB%BA

**Comment by xiquinho** [comment]
done but expect more bugs while I change this page to support the SP.

**Comment by bo-io-gov-mo** [comment]
no show error now, but no result:

http://cn.io.gov.mo/Search/default.aspx?t=B&q=%E5%BD%AD%E6%B7%91%E5%AB%BA&s=d&o=And&sc=f
(9 records match)

http://search2015.io.gov.mo/Search/?q=%E5%BD%AD%E6%B7%91%E5%AB%BA&s=r&t=c&i=s
(9 records match)


http://betan.io.gov.mo/cn/search/?sc=0&tab=b&q=%E5%BD%AD%E6%B7%91%E5%AB%BA&yb=
(tab b: 0 result)

http://betan.io.gov.mo/cn/search/?sc=0&tab=&q=%E5%BD%AD%E6%B7%91%E5%AB%BA
(tab all: 0 result)

may be you are changing search function now cause this issue, I also mark down it.

**Comment by xiquinho** [comment]
I'm fixing the small issues don't have time to fix this yet.

**Comment by xiquinho** [comment]
this error is caused by the function ParseUserInput_jieba which returns 彭~淑~嫺 when the user input 彭淑嫺

**Comment by bo-io-gov-mo** [comment]
yes. pls update the dictionary file:
Bin\Resources\dict.txt 
to:
[dict.zip](https://github.com/bo-io-gov-mo/website/files/448640/dict.zip)

**Comment by xiquinho** [comment]
Just to let you know, I’m renaming the filter sc to o (only title) IF you want to change it on the SP. Sorry for the inconvenience.

**Comment by bo-io-gov-mo** [comment]
noted. I will change it soon.

**Comment by xiquinho** [comment]
btw, is it possible to change the location of theses files to something relative, ie:
/Bin/Resources/dict.txt
instead of
D:\serverwww\n\Bin\Resources\dict.txt

**Comment by bo-io-gov-mo** [comment]
you can try to change in web.config, but I've experience of it.

**Comment by xiquinho** [comment]
ok, I will try. The error is now fixed. pl check.

**Comment by bo-io-gov-mo** [comment]
show error:
http://betan.io.gov.mo/cn/search/?sc=0&tab=a&s=0&q=%E8%91%89%E7%BE%8E%E8%93%AE&n=&y=

**Comment by bo-io-gov-mo** [comment]
fixed.
