### ISSUE TITLE
add a tile into services

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#56]
http://betan.io.gov.mo/cn/services
http://betan.io.gov.mo/pt/services
![image](https://cloud.githubusercontent.com/assets/19220046/18044649/6f571dd8-6e01-11e6-8309-507e307ad221.png)

text cn: **2016年度更改截稿時間通知**
text pt: **Notificação sobre a alteração do fecho do ano de 2016**

link to same pdf: [plan2016.pdf](https://github.com/bo-io-gov-mo/website/files/441961/plan2016.pdf)

**Comment by xiquinho** [comment]
can you change "year 2016" to "current year"?

**Comment by bo-io-gov-mo** [comment]
本年度更改截稿時間通知

**Comment by xiquinho** [comment]
done, pl.check
