### ISSUE TITLE
Search keyword auto complete

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#58]
You already known, I just mark down it.
http://betan.io.gov.mo/cn/search
![image](https://cloud.githubusercontent.com/assets/19220046/18045068/84481592-6e03-11e6-80e4-ac4f53a99867.png)

and this page header not update yet.

**Comment by xiquinho** [comment]
header  done, pl.check

**Comment by bo-io-gov-mo** [comment]
does auto-complete key word is query from db: control\stats, table: stats_search_terms_cn, stats_search_terms_pt? 

I remember it is not update since 2012, how can I update it? I forget where is the most update user search keywords? I want to review and update auto-complete suggestion keyword from last update until now.

**Comment by xiquinho** [comment]
Yes, If I remember correctly, you must change the column active From False to true for the term appear on autosuggest.

**Comment by bo-io-gov-mo** [comment]
Now I know stats_search_terms_cn, stats_search_terms_pt is store keyword for autosuggest.
which table is store user input keyword history?

**Comment by xiquinho** [comment]
stats_search_activity

**Comment by bo-io-gov-mo** [comment]
I got it now, stats_search_terms_cn and stats_search_terms_pt are continuous update when user input keyword. If the keyword as same as before, then add total count. If the keyword is new, then add a new record and set active false. 
It means we need to review those keyword active is false?

**Comment by xiquinho** [comment]
exactly

**Comment by xiquinho** [comment]
auto complete is now ready for test, pl check.

**Comment by xiquinho** [comment]
auto complete is now ready for test on **all tabs**, pl check.

**Comment by bo-io-gov-mo** [comment]
I want to add to field to table:stats_search_terms_cn /pt

- PID (datetime): record update date time.
- Extra (int): for mark down those suggest term is add by us manually, not users input. For example law's exact name and others glossary.

**Comment by xiquinho** [comment]
done, pl check.
