### ISSUE TITLE
update a pdf

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#59]
pls update this pdf only.
http://images.io.gov.mo/cn/about/3_survey2015_cn.pdf
to:
[3_survey2015_cn.pdf](https://github.com/bo-io-gov-mo/website/files/443843/3_survey2015_cn.pdf)

**Comment by xiquinho** [comment]
done, but i think is easier if you update directly, just copy to petaimages and publish to control.

**Comment by bo-io-gov-mo** [comment]
ok
