### ISSUE TITLE
Add 相關連結 Ligações  items

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#6]
![image](https://cloud.githubusercontent.com/assets/19220046/15068608/29a3ae88-13ab-11e6-8bd2-1ab5e2460aeb.png)

![img-506184111](https://cloud.githubusercontent.com/assets/19220046/15068691/a6966b88-13ab-11e6-9bb9-43888abcb7dc.jpg)

1.
澳門特區政府入口網站
http://portal.gov.mo/web/guest/citizen
Portal do Governo de RAE de Macau
http://portal.gov.mo/web/guest/citizen

2.
政府部門專題網站
http://portal.gov.mo/web/guest/info_detail?infoid=791239
Páginas Especializadas dos Serviços Governamentais
http://portal.gov.mo/web/guest/info_detail?infoid=170429

3.
澳門特別行政區法院
http://www.court.gov.mo/zh/
Tribunais da RAEM
http://www.court.gov.mo/pt/

4.
法務局法律推廣
http://www.dsaj.gov.mo/ContentFrame.aspx?ModuleName=Content/tw/law_promote/Main.ascx
Divulgação Jurídica de DSAJ
http://www.dsaj.gov.mo/iis/ContentFrame_pt.aspx?ModuleName=Content/pt/law_promote/LawDoc_pt.ascx

5.
澳門法例資料查詢系統
http://legismac.safp.gov.mo/legismac/main/main.jsf?lang=zh_TW
LegisMac
http://legismac.safp.gov.mo/legismac/main/main.jsf;jsessionid=e4d40b76e7a930361ec2b222c515?lang=pt

6.
漢葡葡漢法律詞彙
http://www.dsaj.gov.mo/Listagem/index.aspx
Glossário Jurídico Chinês-Português/Português-Chinês
http://www.dsaj.gov.mo/Listagem/index.aspx

7.
其他官方印務機構
http://cn.io.gov.mo/Links/Default.aspx
Outras Imprensas Oficiais
http://pt.io.gov.mo/Links/Default.aspx

**Comment by xiquinho** [comment]
ok, done.

**Comment by bo-io-gov-mo** [comment]
The above info have mistake, no.5 LegisMac link should be:
http://legismac.safp.gov.mo/legismac/main/main.jsf?lang=pt

**Comment by xiquinho** [comment]
ok, done.
