### ISSUE TITLE
change mobile website to green theme

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#60]
http://betam.io.gov.mo
![image](https://cloud.githubusercontent.com/assets/19220046/18074930/2920d1c2-6ea3-11e6-917b-268a10b9997e.png)

May I change color theme by myself? I should backup up it first and told you what file changed.

**Comment by xiquinho** [comment]
yes, just remember to checkout the files for edit and when finish check in.

**Comment by bo-io-gov-mo** [comment]
I haven't your Ajax control toolkit and others component. Pls update below files by yourself.
http://betam.io.gov.mo/js/red-theme.min.css
http://betabo.io.gov.mo/mob/js/red-theme.min.css
to:
[red-theme.min.css.zip](https://github.com/bo-io-gov-mo/website/files/444267/red-theme.min.css.zip)

It should change the header and footer to green color.

**Comment by xiquinho** [comment]
done.

**Comment by bo-io-gov-mo** [comment]
There are some css override on style.css, pls update it also:

http://betabo.io.gov.mo/mob/style.css
to:
[style.zip](https://github.com/bo-io-gov-mo/website/files/446274/style.zip)

**Comment by xiquinho** [comment]
done, pl check.
