### ISSUE TITLE
default order of tab B and filters of B records

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#63]
1. pls set the default order by date DESC to tab B, now is default by rank.
http://betan.io.gov.mo/cn/search/?o=0&tab=b&s=1&q=fernando&y=

2. pls set the default order by date DESC to tab B every filters.
http://betan.io.gov.mo/cn/search/?o=0&tab=b&q=fernando&y=&cb=14110&s=1

3. pls set the default order by date DESC to tab ALL of filters of B.
http://betan.io.gov.mo/cn/search/?o=0&tab=&q=fernando&t=b&c=14110&s=1

**Comment by xiquinho** [comment]
Right now you should test only the first tab, sort, pagination and filters, I am waiting for your feedback to finish the other tabs.

**Comment by bo-io-gov-mo** [comment]
ok, the third request is related to the first tab 

3. pls set the default order by date DESC to tab ALL of filters of B.
http://betan.io.gov.mo/cn/search/?o=0&tab=&q=fernando&t=b&c=14110&s=1.

**Comment by xiquinho** [comment]
Are you sure of this?

**Comment by bo-io-gov-mo** [comment]
yes, tab B date is default by date desc, only tab b filters.

**Comment by xiquinho** [comment]
done

**Comment by xiquinho** [comment]
sorry, I misread this, I thought it was an issue, not a request. pl. check now.
