### ISSUE TITLE
missing pagination at private entity  

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#64]
missing pagination at private entity, for example:
http://betan.io.gov.mo/cn/entities/priv/cat/commercial

**Comment by xiquinho** [comment]
this is done, pl. check. I'm converting the sql strings to parameter queries, I hope not, but you may find an error somewhere. Pl. let me know if any.

**Comment by bo-io-gov-mo** [comment]
I see the pagination now, but it show duplication name on navigation bar of page 2:

http://betan.io.gov.mo/cn/entities/priv/cat/commercial/?p=2&
![image](https://cloud.githubusercontent.com/assets/19220046/18333816/0d7af9a8-75a5-11e6-8ea0-0eb9774d994d.png)

**Comment by xiquinho** [comment]
my mistake, is ok now but I had to make a few changes except more some errors somewhere while I don't finish.

**Comment by xiquinho** [comment]
done, pl check

**Comment by xiquinho** [comment]
missing something?
