### ISSUE TITLE
missing yellow highline of keyword on search result

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#67]
Before have, now disappear. for example:
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=%E6%BE%B3%E9%96%80%E5%A4%A7%E5%AD%B8

**Comment by xiquinho** [comment]
didn't you told me to remove?

**Comment by bo-io-gov-mo** [comment]
no

**Comment by xiquinho** [comment]
no prob, I will put it again.

**Comment by bo-io-gov-mo** [comment]
thanks. :)

**Comment by xiquinho** [comment]
You'r welcome! done, pl check.
