### ISSUE TITLE
search rank of diplomlvl adjust

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#69]
I'm trying to adjust the adjust diplomlvl of text_rank order, to optimize this cases: (the title name not same as inside text's title)
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=%E5%B7%A5%E7%A8%8B%E3%80%81%E5%8F%96%E5%BE%97%E8%B2%A1%E8%B2%A8%E5%8F%8A%E5%8B%9E%E5%8B%99%E4%B9%8B%E9%96%8B%E6%94%AF%E5%88%B6%E5%BA%A6

SP GetFilteredTable_all_cn /pt
from:
````
...
(CASE WHEN title_Rank > 0 THEN tbl_rank.title_Rank+isNull(FT_TBL.diplomlvl,0)*100 ELSE tbl_rank.title_Rank END) AS [Rank], 
FT_TBL.diplomlvl, 
tbl_rank.text_Rank,
...
````
to 
````
...
(CASE WHEN title_Rank > 0 THEN tbl_rank.title_Rank+isNull(FT_TBL.diplomlvl,0)*100 ELSE tbl_rank.title_Rank END) AS [Rank], 
FT_TBL.diplomlvl, 
tbl_rank.text_Rank,
 (CASE WHEN tbl_rank.text_Rank > 0 THEN tbl_rank.text_Rank+isNull(FT_TBL.diplomlvl,0)*100 ELSE tbl_rank.text_Rank END) AS text_Rank,
...
````

I will tell you change TAB A query or not later.

**Comment by xiquinho** [comment]
Ok, right now I don't do anything.

**Comment by bo-io-gov-mo** [comment]
pls update your sql query of TAB A:  [commented 9 days ago](https://github.com/bo-io-gov-mo/website/issues/35#issuecomment-243020869)

find :
````
...
 (CASE WHEN title_Rank > 0 THEN KEY_TBL.title_Rank+isNull(FT_TBL.Visits_cn,0)*100 ELSE KEY_TBL.title_Rank END) AS [Rank],
**
KEY_TBL.Text_RANK, 
**
FT_TBL.DipOrder 
FROM tbo2004 As FT_TBL
INNER JOIN (
...
````
to:
```
...
 (CASE WHEN title_Rank > 0 THEN KEY_TBL.title_Rank+isNull(FT_TBL.Visits_cn,0)*100 ELSE KEY_TBL.title_Rank END) AS [Rank],
**
 (CASE WHEN KEY_TBL.text_Rank > 0 THEN KEY_TBL.text_Rank+isNull(FT_TBL.Visits_cn,0)*100 ELSE KEY_TBL.text_Rank END) AS text_Rank,
**
FT_TBL.DipOrder 
FROM tbo2004 As FT_TBL 
INNER JOIN (
...
````

**Comment by xiquinho** [comment]
only tab A? or you mean all others?

**Comment by bo-io-gov-mo** [comment]
In your query I think only TAB A use diplomlvl(Visits_cn).

**Comment by xiquinho** [comment]
Ok, tab A query is as following:

With result_set As (Select ROW_NUMBER() OVER ( ORDER BY (Case When KEY_TBL.title_Rank > 0 Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, text_Rank DESC, DatePublished DESC ) AS [row_number], FT_TBL.DiplomNamept AS DipName, FT_TBL.DiplomDescpt AS DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab, KEY_TBL.Title_RANK as [RANK] FROM tbo2004 As FT_TBL INNER JOIN ( SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_pt, N' "macau"',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_pt, N' "macau"',language 1033) ) as T INNER JOIN Search as S on T.[key]=S.tboID GROUP BY S.tboID, S.LinkID, S.tab ) AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='a') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) Select * FROM result_set WHERE [row_number] BETWEEN 0 And 24

But I can find the string that match the find. Can you please mark in **bold** what you want exactly to replace?

**Comment by bo-io-gov-mo** [comment]
With result_set As (Select ROW_NUMBER() OVER ( ORDER BY (Case When KEY_TBL.title_Rank > 0 Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, ****text_Rank** DESC, DatePublished DESC ) AS [row_number], FT_TBL.DiplomNamept AS DipName, FT_TBL.DiplomDescpt AS DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab, KEY_TBL.Title_RANK as [RANK] FROM tbo2004 As FT_TBL INNER JOIN ( SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_pt, N' "macau"',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_pt, N' "macau"',language 1033) ) as T INNER JOIN Search as S on T.[key]=S.tboID GROUP BY S.tboID, S.LinkID, S.tab ) AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='a') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) Select * FROM result_set WHERE [row_number] BETWEEN 0 And 24


modify **text_Rank** 
to:
**(Case When KEY_TBL.text_Rank > 0 Then KEY_TBL.text_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.text_Rank End)**

**Comment by xiquinho** [comment]
Ok, got it now, only to change the ORDER BY clause.

BTW, I’m trying to build a query to simplify the other tabs something like this:

SELECT name, year
	FROM Table
	CASE 
		When @year = '' THEN Where year = '0'
		When @year <> '' THEN Where year = @year
	END

I know this don’t work but I need something like this. Do you have any idea how can I do this? Or with something similar?

**Comment by bo-io-gov-mo** [comment]
I don't understand exactly, may be below help for reference:
http://stackoverflow.com/questions/10191424/case-in-where-sql-server

declare @year int
set @year = ''

SELECT top 10 linkid, codeYear
FROM tbo2004
where codeYear = CASE @Year When '' THEN  0  Else @year END


SELECT top 10 linkid, codeYear
FROM tbo2004
where codeYear = CASE @Year When '' THEN  codeYear  Else @year END

**Comment by xiquinho** [comment]
ty, I will take a look.

**Comment by bo-io-gov-mo** [comment]
only tab A? or you mean **all others**?

The simple answer is YES change the query for **all others**. But it only affect Tab A records now.

**Comment by xiquinho** [comment]
OK

**Comment by xiquinho** [comment]
done, pl check

**Comment by bo-io-gov-mo** [comment]
perfect.
