### ISSUE TITLE
finish agency information

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#7]
http://betan.io.gov.mo/cn/entities/admpub/rec/10110
![image](https://cloud.githubusercontent.com/assets/19220046/15104010/c342edac-15e4-11e6-900e-33a248cfa5b0.png)

http://pt.io.gov.mo/Legis/record/10110.aspx
![image](https://cloud.githubusercontent.com/assets/19220046/15104038/f56549f6-15e4-11e6-9efd-6349efe0b47f.png)

**Comment by xiquinho** [comment]
ok, done.

**Comment by bo-io-gov-mo** [comment]
The second and third table show rows too long, will make a paginate like before is better?
![image](https://cloud.githubusercontent.com/assets/19220046/15174975/c7d1f8be-1796-11e6-9cbb-0fe95896ba5c.png)

**Comment by xiquinho** [comment]
how many records do you want per page?

**Comment by bo-io-gov-mo** [comment]
now is 10, for me is ok.

**Comment by xiquinho** [comment]
10 year ago, 10 records per page was ok, in 2016 is just silly. Modern browsers and devices support much more than that. But I digress... 10 will be.

**Comment by xiquinho** [comment]
ok, done.

**Comment by bo-io-gov-mo** [comment]
I look now is better, thanks for your cooperation.
