### ISSUE TITLE
search input error

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#70]
when input ' + - * / ? show server error.

http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=%27

**Comment by xiquinho** [comment]
I don't fix yet the special char, later will sent a list for you review.

**Comment by bo-io-gov-mo** [comment]
pt no error, cn have error.

**Comment by xiquinho** [comment]
I include this function to remove special char and htmal from user input, pl let me know if you want to add or remove any:

    Public Shared Function StripforFTS(ByVal str As String) As String
        'to remove
        str = Replace(str, """", "")
        str = Replace(str, "!", "")
        str = Replace(str, "?", "")
        str = Replace(str, "+", "")
        str = Replace(str, "*", "")
        str = Replace(str, ":", "")
        str = Replace(str, ";", "")
        str = Replace(str, "& ", "")
        str = Replace(str, "&", "")
        str = Replace(str, ".", "")
        str = Replace(str, ",", "")
        str = Replace(str, "--", "-")
        str = Regex.Replace(str, "[-#!£$%^&*()\\]+?", String.Empty)
        str = Regex.Replace(str, "</?[hH]3[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[div[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[DIV[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[i[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[p[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[b[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[P[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[B[^>]*>", String.Empty)
        str = Regex.Replace(str, "</?[em[^>]*>", String.Empty)
        str = Regex.Replace(str, "", String.Empty)
        str = Regex.Replace(str, "<(.|\s)*?>", String.Empty)
        str = Replace(str, """", String.Empty)
        'to keep
        str = Regex.Replace(str, "[^0-9a-zA-Z ]+?", String.Empty)
        Return str
    End Function

**Comment by bo-io-gov-mo** [comment]
no supplement now.
