### ISSUE TITLE
search display syntax

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#72]
It is display problem:
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=a
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=b
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=h

**Comment by xiquinho** [comment]
fixed for single character searches, maybe have more similar.
