### ISSUE TITLE
missing icon pic

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#73]
pls see chrome developer console 404: http://betan.io.gov.mo/cn/home/

http://images.io.gov.mo/images/2016/logoraem.svg
http://images.io.gov.mo/images/2016/logoio.svg

**Comment by xiquinho** [comment]
It's the code and the pictures YOU send to me, this is not my code, this is not my choice.

**Comment by bo-io-gov-mo** [comment]
you haven't those svg file?

**Comment by xiquinho** [comment]
It's the svg file. The error is caused by the svg file.

**Comment by bo-io-gov-mo** [comment]
the error is missing svg files.

**Comment by xiquinho** [comment]
ask Jon to upload to images server, I only have tit_io.svg file, the other are missing.

**Comment by bo-io-gov-mo** [comment]
ok

**Comment by bo-io-gov-mo** [comment]
I got the problem now, pls change your code:

from:
````
<img target="_top" class="img-responsive center-block headerlogos" 
alt="澳 門 特 別 行 政 區 政 府" 
src="/pt/content/images/logoraem.png" 
onerror="this.src = '/pt/content/images/logoraem.png'">
````
to:
src="/pt/content/images/logoraem.**svg**"

-----------------

and from:
````
<img class="img-responsive center-block headerlogos" alt="印 務 局" 
src="/pt/content/images/logoio.png" 
onerror="this.src = '/pt/content/images/logoio.png'">
````
to:
src="/pt/content/images/logoio.**svg**"

**Comment by xiquinho** [comment]
ok, let me check

**Comment by bo-io-gov-mo** [comment]
fixed.
