### ISSUE TITLE
search tab A filter order by DiplomOrder adjust

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#76]
pls change the order by DiplomOrder in sql query filterA_str: 

SELECT COUNT(FT_TBL.LinkID) AS TotalRecs, DiplomTypes.DiplomNamecn AS CatName, DiplomTypes.TypeID FROM tbo2004 AS FT_TBL INNER JOIN DiplomTypes ON FT_TBL.DipCodedb = DiplomTypes.DiplomCode INNER JOIN ( SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_cn, N'macau',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_cn, N'macau',language 1033) ) as T INNER JOIN Search as S on T.[key]=S.tboID GROUP BY S.tboID, S.LinkID, S.tab ) AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='a') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 **Group BY DiplomTypes.DiplomNamecn, DiplomTypes.TypeID ORDER BY TotalRecs DESC**

to:
**Group BY DiplomTypes.DiplomNamecn, DiplomTypes.TypeID,DiplomTypes.DiplomOrder ORDER BY DiplomTypes.DiplomOrder DESC**

**Comment by xiquinho** [comment]
done

**Comment by bo-io-gov-mo** [comment]
sorry pls remove last **DESC**

**Comment by xiquinho** [comment]
done
