### ISSUE TITLE
Add search function

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#8]
as i send before, use **control\Bo2004_search\** database for chinese fts index source data. It is [Jieba.Net](https://github.com/anderscui/jieba.NET) for chinese word segment cutter.

example website: [search2015.io.gov.mo/search](http://search2015.io.gov.mo/search)

[[project download]](https://www.dropbox.com/s/vxkpcnc3j1l7cld/betas.zip?dl=0)

**Comment by bo-io-gov-mo** [comment]
Regard to search2015 global filter for result, I expect include common field(BoNo, Year, Serie…), beside include a CATEGORY filter. For ‘TableA’ may be DiplomCode, for ‘TABLEB’ is Category.catID.
Screen and filter like:
![image](https://cloud.githubusercontent.com/assets/19220046/15105820/6504151e-15f7-11e6-8608-b0c7201c6d57.png)


You can migrate your most existing filter to new search logic, for example:

Orginal: http://betacn.io.gov.mo/Search/default.aspx?t=A&q=%E6%9D%9C%E5%BF%97%E6%96%87&s=r&o=And&sc=f
SELECT FT_TBL.DiplomNamecn, FT_TBL.DiplomDesccn, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, 
KEY_TBL.RANK , FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento 
FROM tbo2004 AS FT_TBL 
**INNER JOIN CONTAINSTABLE(tbo2004, (DiplomNamecn, DiplomDesccn, Textcn), '"杜志文"', LANGUAGE N'Traditional Chinese') AS KEY_TBL 
ON FT_TBL.tboID = KEY_TBL.[KEY]**
WHERE FT_TBL.Active = 'True' 
ORDER BY RANK DESC

change to: 
   
 SELECT FT_TBL.DiplomNamecn, FT_TBL.DiplomDesccn, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, 
 KEY_TBL.Title_RANK , FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento 
 FROM tbo2004 AS FT_TBL 
**INNER JOIN (
    SELECT SUM(t.Title_Rank) AS Title_RANK, 
    SUM(t.text_Rank) AS Text_RANK, s.tboID,s.LinkID,s.cat FROM 
    (
    SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank 
    FROM CONTAINSTABLE(search, jieba_title, N'"杜志文"',language 1033) 
    UNION ALL 
    SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank
    FROM CONTAINSTABLE(search, jieba_textcn, N'"杜志文"',language 1033) 
    ) as t inner join Search as s on t.[key]=s.tboID GROUP BY s.tboID, s.LinkID, s.cat
    )AS KEY_TBL
   on (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.cat='A')**
 WHERE FT_TBL.Active = 'True' 
 ORDER BY Title_RANK,Text_RANK DESC

**Comment by xiquinho** [comment]
I got an error when trying to merge your project with mine, not sure how can I fix this, any ideas?

![prob_trans_error](https://cloud.githubusercontent.com/assets/3314293/15733685/d5309bca-28ba-11e6-9d1c-100cebcf75ab.png)

**Comment by leumaslau** [comment]
The reason is that JiebaNet.Segmenter cannot find the required resource files. Here is the solution:

1. Download and place the resource files into the bin folder
    [Resources.zip](https://github.com/bo-io-gov-mo/website/files/294809/Resources.zip)

2. Add the following keys into web.confg **appSettings** section
    `<add key="MainDictFile" value="project_location\bin\Resources\dict.txt" />`
    `<add key="ProbTransFile" value="project_location\bin\Resources\prob_trans.json" />`
    `<add key="ProbEmitFile" value="project_location\bin\Resources\prob_emit.json" />`
    `<add key="PosProbStartFile" value="project_location\bin\Resources\pos_prob_start.json" />`
    `<add key="PosProbTransFile" value="project_location\bin\Resources\pos_prob_trans.json" />`
    `<add key="PosProbEmitFile" value="project_location\bin\Resources\pos_prob_emit.json" />`
    `<add key="CharStateTabFile" value="project_location\bin\Resources\char_state_tab.json" />`
    `<add key="StopWordsFile" value="project_location\bin\Resources\stopwords.txt" />`
    `<add key="IdfFile" value="project_location\bin\Resources\idf.txt" />`
    `<add key="IODict" value="project_location\bin\Resources\io_dict.txt" />`
    Set the values to the location of the resource files

**Comment by xiquinho** [comment]
ty, it looks fine now.

**Comment by xiquinho** [comment]
except for the sql server>  connectionString="Data Source=192.168.3.63; User ID=sa; Password=12345678; Initial Catalog=bo2004"  can't access it:

**Comment by xiquinho** [comment]
![sqlser-error](https://cloud.githubusercontent.com/assets/3314293/15734334/1f482eb6-28c1-11e6-8fa9-169d289d5906.png)

**Comment by bo-io-gov-mo** [comment]
can point to control\bo2004_search database?

**Comment by leumaslau** [comment]
ya it should point to the control\bo2004_search database

**Comment by xiquinho** [comment]
thanks, it is fine now.

**Comment by xiquinho** [comment]
On Control -> Bo2004_search -> Search table, Can you please:

Rename column cat to tab
Rename column jieba_title to title_cn
Rename column jieba_textcn to text_cn
Add column title_pt
Add column text_pt

and fill these columns with portuguese text and titles, just like the chinese?

TY!!!

**Comment by bo-io-gov-mo** [comment]
It is ok. Need to modify the schedule program of update data first. Samuel on holiday, change it on next wednesday.

**Comment by xiquinho** [comment]
ty, is OK I still have many things to do on search.

**Comment by bo-io-gov-mo** [comment]
column name already changed.

**Comment by bo-io-gov-mo** [comment]
we have some enhance change of the search code of previous project.
1. Any update of your search function implement.
2. I want update some query code, how can I give to you are convenience.

**Comment by xiquinho** [comment]
> update of your search function implement.
> 2. I want update some

**Comment by xiquinho** [comment]
after you renamed the columns your old sql query doesn't work anymore, I am not sure why.

Can you send me the new query just like you send before?

**Comment by bo-io-gov-mo** [comment]
here sql query, replace the field name only: 
http://search2015.io.gov.mo/Search/?q=%E6%BE%B3%E9%96%80%E7%89%B9%E5%88%A5%E8%A1%8C%E6%94%BF%E5%8D%80&s=r&t=c&i=s


...... CONTAINSTABLE(search, **title_cn**, N'澳門特別行政區',language 1033) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, **text_cn**, N'澳門特別行政區',language 1033))......

**Comment by bo-io-gov-mo** [comment]
We had some changed user KEYWORD process function and default dictionary for optimize result, project history detail at : 
http://192.168.3.22:8080/tfs/DefaultCollection/_git/betas?_a=history

**Comment by xiquinho** [comment]
what is the meaning/intention of "language 1033" on the Chinese query? Shouldn't it be 950?

**Comment by bo-io-gov-mo** [comment]
https://msdn.microsoft.com/en-us/library/ms176076.aspx
LCID 1033 is English
LCID 1028 is Traditional Chinese

I use 1033 because setting sql server process word behaviour like english, with already word break field "title_cn" & "text_cn" with Jieba.

I do it was assume "Jeiba" word breaker is better or suitable then which sql server build in word breaker.

**Comment by xiquinho** [comment]
Yes, I mean 1028, but if it is correct Ok, don't mind abou it,

One morre thing: I already finish the filters and they work fine alone, but I am having trouble for them work together with your query.

I need to include in the query something like this:

.... WHERE FT_TBL.active, = 'true' AND (bla, bla,bla,...) AND (bla, bla,bla,...)

but in your view there is not the active column. (and it must have, otherwise the search will include unintended records), also I am not sure where exactly include the condition.

**Comment by bo-io-gov-mo** [comment]
I don't know what is your FT_TBL, if it means view "vwIndexQuery" inside condition already have " where active=1 ..."(see it design). Otherwise can add/select "active" column in vwIndexQuery. what you want?

**Comment by xiquinho** [comment]
FT_TBL means foreign table, because it could be any of the 3 tables for BO records. In the query you are using at search2015.io.gov.mo I don't see " where active=1 ..." anywhere. I assume this is the same query I will use in the new search, take a look at:

http://search2015.io.gov.mo/Search/?q=%E6%BE%B3%E9%96%80%E7%89%B9%E5%88%A5%E8%A1%8C%E6%94%BF%E5%8D%80&s=r&t=c&i=s

where is the " where active = 1 ..." ? I can't see it...

If you don't include this in the query, hidden records might appear on the search.

**Comment by bo-io-gov-mo** [comment]
search2015 sql query FT_TBL is use **vwIndexQuery** (which is a view table only include ALL 3 table record and active=1): 
````
... FT_TBL.DatePublished FROM vwIndexQuery AS FT_TBL INNER JOIN ...
````

for example your FT_TBL is only bo2004, you can reference above secondary comment post.

**Comment by xiquinho** [comment]
ok, I will use the same query without the active=1. ty!

**Comment by bo-io-gov-mo** [comment]
Remind you that I assume portuguese search word or phrase logic may be different of chinese, you test portugese search result as you expect or not. Chinese search you provide for me test it ASAP. When you can provide it? I think it may be many adjustment.

**Comment by xiquinho** [comment]
I just upload a beta version for testing, it is still buggy and need a code cleaning and improving but I think is ready for test. Pl help to test the filters and let me know if you want to change something before I make the cleaning.

**Comment by xiquinho** [comment]
http://betan.io.gov.mo/cn/search/

http://betan.io.gov.mo/pt/search/

**Comment by bo-io-gov-mo** [comment]
chinese search error.

**Comment by xiquinho** [comment]
it's a server error, let me check

**Comment by xiquinho** [comment]
pl try now
