### ISSUE TITLE
add and keep existing RSS function.

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#9]
http://cn.io.gov.mo/RSS/Default.aspx

![image](https://cloud.githubusercontent.com/assets/19220046/15107504/af68be2e-1602-11e6-9889-207f373316d4.png)

**Comment by xiquinho** [comment]
ok, pl. test and let me know if you find any error. Same for International Law.

**Comment by bo-io-gov-mo** [comment]
Noted, we will look it.

**Comment by xiquinho** [comment]
did you look it? need any change? if not pl. close.
